"""add start to segments

Revision ID: 0c681bccb387
Revises: cc6bb3ed8755
Create Date: 2026-05-15 15:06:56.528207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c681bccb387'
down_revision: Union[str, None] = 'cc6bb3ed8755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segments', sa.Column('start', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segments', 'start')
    # ### end Alembic commands ###
