"""add url mediatree to segments table

Revision ID: 3a14dba62ea0
Revises: bc36211e6553
Create Date: 2026-05-26 11:05:10.173079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a14dba62ea0'
down_revision: Union[str, None] = 'bc36211e6553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segments', sa.Column('url_mediatree', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segments', 'url_mediatree')
    # ### end Alembic commands ###
