"""add start to segments

Revision ID: 6ba0bd400f99
Revises: cc6bb3ed8755
Create Date: 2026-05-15 16:47:55.267460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba0bd400f99'
down_revision: Union[str, None] = 'cc6bb3ed8755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segments', sa.Column('start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('segments', sa.Column('channel_name', sa.String(), nullable=True))
    op.add_column('segments', sa.Column('channel_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segments', 'channel_title')
    op.drop_column('segments', 'channel_name')
    op.drop_column('segments', 'start')
    # ### end Alembic commands ###
