"""add unique constraints for segment and case upserts

Revision ID: 937031dc7d99
Revises: c3516c0fa264
Create Date: 2026-05-27 07:48:00.568868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937031dc7d99'
down_revision: Union[str, None] = 'c3516c0fa264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cases_case_segment_subject', 'cases', ['case_id', 'segment_id', 'subject_id'])
    op.create_unique_constraint('uq_segments_segment_subject', 'segments', ['segment_id', 'subject_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_segments_segment_subject', 'segments', type_='unique')
    op.drop_constraint('uq_cases_case_segment_subject', 'cases', type_='unique')
    # ### end Alembic commands ###
