"""add start to cases

Revision ID: a406a239ee98
Revises: 6ba0bd400f99
Create Date: 2026-05-18 16:17:34.183662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a406a239ee98'
down_revision: Union[str, None] = '6ba0bd400f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('start', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'start')
    # ### end Alembic commands ###
