"""add 
  text col to cases table

Revision ID: bc36211e6553
Revises: a406a239ee98
Create Date: 2026-05-18 18:27:34.948962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc36211e6553'
down_revision: Union[str, None] = 'a406a239ee98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'text')
    # ### end Alembic commands ###
