"""add labelstudio url to cases

Revision ID: c3516c0fa264
Revises: 3a14dba62ea0
Create Date: 2026-05-27 07:26:03.293335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3516c0fa264'
down_revision: Union[str, None] = '3a14dba62ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('url_labelstudio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'url_labelstudio')
    # ### end Alembic commands ###
