"""add subject_id to dictionary

Revision ID: cc6bb3ed8755
Revises: f0127e34c36d
Create Date: 2026-05-15 14:10:32.422121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc6bb3ed8755'
down_revision: Union[str, None] = 'f0127e34c36d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary', sa.Column('subject_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'dictionary', 'subjects', ['subject_id'], ['subject_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dictionary', type_='foreignkey')
    op.drop_column('dictionary', 'subject_id')
    # ### end Alembic commands ###
