"""add rrs tables

Revision ID: f0127e34c36d
Revises: 
Create Date: 2026-05-15 12:50:11.804455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0127e34c36d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary',
    sa.Column('keyword_id', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('high_risk_false_positive', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() at time zone 'utc')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('keyword_id')
    )
    op.create_table('subjects',
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() at time zone 'utc')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('clusters',
    sa.Column('cluster_id', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=True),
    sa.Column('cluster_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() at time zone 'utc')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    op.create_table('segments',
    sa.Column('segment_id', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=True),
    sa.Column('s3_uri', sa.String(), nullable=True),
    sa.Column('n_keywords', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() at time zone 'utc')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('segment_id')
    )
    op.create_table('cases',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('segment_id', sa.String(), nullable=True),
    sa.Column('subject_id', sa.String(), nullable=True),
    sa.Column('model_score', sa.String(), nullable=True),
    sa.Column('model_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() at time zone 'utc')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.segment_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('case_to_clusters',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('cluster_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() at time zone 'utc')"), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.cluster_id'], ),
    sa.PrimaryKeyConstraint('case_id', 'cluster_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_to_clusters')
    op.drop_table('cases')
    op.drop_table('segments')
    op.drop_table('clusters')
    op.drop_table('subjects')
    op.drop_table('dictionary')
    # ### end Alembic commands ###
