"""add metadata to cases and segments

Revision ID: f32e36816995
Revises: a7c3f1e9b2d4
Create Date: 2026-06-24 13:51:52.400105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f32e36816995'
down_revision: Union[str, None] = 'a7c3f1e9b2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('is_labeled', sa.Boolean(), nullable=True))
    op.add_column('cases', sa.Column('mesinfo_choice', sa.String(), nullable=True))
    op.add_column('segments', sa.Column('channel_program', sa.String(), nullable=True))
    op.add_column('segments', sa.Column('keywords', postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segments', 'keywords')
    op.drop_column('segments', 'channel_program')
    op.drop_column('cases', 'mesinfo_choice')
    op.drop_column('cases', 'is_labeled')
    # ### end Alembic commands ###
