"""add language column

Revision ID: d69c4dcaca98
Revises: m7n8o9p0q1r2
Create Date: 2026-03-13 16:58:18.451393

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd69c4dcaca98'
down_revision = 'm7n8o9p0q1r2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyword_macro_category', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keyword_macro_category', 'language')
    # ### end Alembic commands ###


