FROM python:3.10-buster

RUN pip install poetry==1.4.2

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /app

COPY pyproject.toml poetry.lock ./
RUN touch README.md

RUN poetry install --without dev --no-root --no-interaction --no-ansi && rm -rf $POETRY_CACHE_DIR

COPY . .

RUN poetry install --without dev

ENTRYPOINT ["poetry", "run", "python", "quotaclimat/data_ingestion/ingest_db/ingest_sitemap_in_db.py", "-p ${{ secrets.D4G_VM_DB_PWD }"]