MAPPING_PROGRAMMES_CATEGORIES = {
    "série dramatique": "divertissement",
    "autre": "autre",
    "magazine jeunesse": "jeunesse",
    "météo": "méteo",
    "magazine de télé-achat": "divertissement",
    "téléréalité": "divertissement",
    "feuilleton sentimental": "divertissement",
    "magazine de la gastronomie": "divertissement",
    "divertissement : jeu": "divertissement",
    "journal": "journal",
    "film sentimental": "divertissement",
    "téléfilm sentimental": "divertissement",
    "divertissement-humour": "divertissement",
    "série policière": "divertissement",
    "débat": "debat",
    "documentaire société": "documentaire",
    "téléfilm dramatique": "divertissement",
    "magazine religieux": "magazine",
    "documentaire découvertes": "documentaire",
    "feuilleton policier": "divertissement",
    "magazine de services": "magazine",
    "magazine de société": "magazine",
    "magazine du consommateur": "magazine",
    "magazine d'information": "magazine",
    "magazine littéraire": "magazine",
    "magazine de l'art de vivre": "magazine",
    "magazine de la décoration": "magazine",
    "magazine musical": "magazine",
    "sport : rugby": "sport",
    "magazine de reportages": "magazine",
    "magazine de la mer": "magazine",
    "magazine de découvertes": "magazine",
    "feuilleton réaliste": "divertissement",
    "jeunesse : dessin animé dessin animé": "divertissement",
    "série d'animation": "divertissement",
    "jeunesse : dessin animé jeunesse": "divertissement",
    "magazine régional": "magazine",
    "magazine culinaire": "magazine",
    "sport : multisports": "sport",
    "magazine sportif": "sport",
    "téléfilm policier": "divertissement",
    "série historique": "divertissement",
    "documentaire culture": "documentaire",
    "film : court métrage": "divertissement",
    "sport : golf": "sport",
    "magazine du cinéma": "magazine",
    "divertissement": "divertissement",
    "film : thriller": "divertissement",
    "film : drame historique": "divertissement",
    "magazine d'actualité": "divertissement",
    "film fantastique": "divertissement",
    "talk-show": "magazine",  # TODO check
    "film : drame": "divertissement",
    "documentaire animalier": "documentaire",
    "documentaire musique": "documentaire",
    "documentaire histoire": "documentaire",
    "documentaire santé": "documentaire",
    "magazine du tourisme": "magazine",
    "documentaire politique": "documentaire",
    "film d'aventures": "divertissement",
    "documentaire nature": "documentaire",
    "documentaire environnement": "documentaire",
    "magazine de géopolitique": "magazine",
    "documentaire gastronomie": "documentaire",
    "programme indéterminé": "autre",
    "clips": "divertissement",
    "série humoristique": "divertissement",
    "magazine culturel": "magazine",
    "musique : techno": "divertissement",
    "sport : fitness": "sport",
    "interview": "magazine",  # TODO check
    "film catastrophe": "divertissement",
    "magazine du show-biz": "magazine",
    "série sentimentale": "divertissement",
    "film d'animation": "divertissement",
    "série fantastique": "divertissement",
    "humour": "divertissement",
    "jeunesse : emission jeunesse": "magazine",  # TODO check
    "série culinaire": "divertissement",
    "série jeunesse": "divertissement",
    "magazine médical": "magazine",
    "théâtre : pièce de théâtre": "divertissement",
    "débat parlementaire": "magazine",  # TODO check
    "magazine politique": "magazine",
    "emission politique": "magazine",
    "magazine de l'économie": "magazine",
    "documentaire téléréalité": "documentaire",
    "magazine de l'environnement": "magazine",
    "magazine éducatif": "magazine",
    "téléfilm romanesque": "divertissement",
    "série réaliste": "divertissement",
    "film de science-fiction": "divertissement",
    "film d'action": "divertissement",
    "magazine de l'automobile": "magazine",
    "sport de force": "sport",
    "sport : football": "sport",
    "sport : basket-ball": "sport",
    "documentaire justice": "documentaire",
    "sport : hippisme": "sport",
    "documentaire sciences et technique": "documentaire",
    "magazine judiciaire": "magazine",
    "magazine de la santé": "magazine",
    "film : comédie sentimentale": "divertissement",
    "musique : pop %26 rock": "divertissement",
    "musical": "divertissement",
    "musique : variétés": "divertissement",
    "film : comédie romantique": "divertissement",
    "film : court métrage d'animation": "divertissement",
    "sport : formule 1": "sport",
    "documentaire civilisations": "documentaire",
    "magazine historique": "magazine",
    "téléfilm de suspense": "divertissement",
    "documentaire rock-pop": "documentaire",
    "documentaire cinéma": "documentaire",
    "documentaire education": "documentaire",
    "magazine des médias": "magazine",
    "série d'aventures": "divertissement",
    "film : comédie": "divertissement",
    "documentaire pêche": "documentaire",
    "documentaire voyage": "documentaire",
    "documentaire aventures": "documentaire",
    "documentaire beaux-arts": "documentaire",
    "loterie": "divertissement",
    "sport : jt sport": "sport",
    "film d'horreur": "divertissement",
    "série d'action": "divertissement",
    "musique : reggae": "divertissement",
    "magazine de l'emploi": "magazine",
    "musique : contemporain": "divertissement",
    "musique : jazz": "divertissement",
    "opéra comique": "divertissement",
    "téléfilm fantastique": "divertissement",
    "jeunesse : dessin animé manga": "divertissement",
    "série de science-fiction": "divertissement",
    "sport : biathlon": "sport",
    "sport : endurance": "sport",
    "magazine du jardinage": "magazine",
    "sports mécaniques": "sport",
    "emission religieuse": "magazine",  # TODO check
    "documentaire art de vivre": "documentaire",
    "film de guerre": "divertissement",
    "sport : voile": "sport",
    "film : comédie dramatique": "divertissement",
    "documentaire sport": "documentaire",
    "magazine du court métrage": "magazine",
    "film : court métrage dramatique": "divertissement",
    "film policier": "divertissement",
    "documentaire musique classique": "documentaire",
    "magazine scientifique": "magazine",
    "emission du bien-être": "divertissement",
    "magazine animalier": "magazine",
    "sport : mma": "sport",
    "sport : ski freestyle": "sport",
    "sport : cyclo-cross": "sport",
    "sport : football américain": "sport",
    "documentaire géopolitique": "sport",
    "téléfilm humoristique": "divertissement",
    "musique : classique": "divertissement",
    "série de téléréalité": "divertissement",
    "documentaire fiction": "documentaire",
    "téléfilm érotique": "divertissement",
}
