server {
    listen 8080;

    resolver 8.8.8.8 ipv6=off;

    # In order for those var env to be replaced at run time, this file should be placed as an nginx template. See Dockerfile
    location /${INTERCEPT_PATH}/ {
        proxy_pass ${INTERCEPT_PROXY_PASS}/;
    }
    location / {
        proxy_pass ${DEFAULT_PROXY_PASS};
    }
}