id: barometre
namespace: quotaclimat-dev

tasks:
  - id: ingest_data_to_s3
    type: io.kestra.plugin.docker.Run
    containerImage: "{{ envs.container_registry_barometre }}:latest"
    pullPolicy: ALWAYS
    credentials:
      registry: "{{ envs.container_registry_barometre }}"
      username: nologin
      password: "{{ secret('SCW_SECRET') }}"
    entryPoint:
      - python
      - quotaclimat/data_processing/mediatree/s3/api_to_s3.py
    shmSize: 2gb
    env: 
      API_TO_S3_CONCURRENCY: 10
      BUCKET_NAME: test-bucket-mediatree
      COUNTRY: all
      ENV: prod
      KEYWORDS_URL: https://keywords.mediatree.fr/api/subtitle/
      LOGLEVEL: INFO
      MEDIATREE_AUTH_URL: https://keywords.mediatree.fr/api/auth/token/
      MEDIATREE_USER: quotaclimat
      MODIN_CPUS: 2
      MODIN_ENGINE: ray
      MODIN_MEMORY: 2000000000
      OMP_NUM_THREADS: 3
      PORT_HS: 5666
      BUCKET: "{{ secret('SCW_ACCESS') }}"
      BUCKET_SECRET: "{{ secret('SCW_SECRET') }}"
      MEDIATREE_PASSWORD: "{{ secret('MEDIATREE_PASSWORD') }}"
      SENTRY_DSN: "{{ secret('SENTRY_DSN') }}"

  - id: detect_keywords
    shmSize: 2gb
    type: io.kestra.plugin.docker.Run
    containerImage: "{{ envs.container_registry_barometre }}:latest"
    pullPolicy: ALWAYS
    credentials:
      registry: "{{ envs.container_registry_barometre }}"
      username: nologin
      password: "{{ secret('SCW_SECRET') }}"
    entryPoint:
      - ./entrypoints/detect_keywords.sh
    env:
      BATCH_SIZE: 5000
      BUCKET_NAME: test-bucket-mediatree
      COMPARE_DURATION: true
      COUNTRY: all
      DBT_PROFILES_DIR: /app/my_dbt_project/dbt
      DBT_PROJECT_DIR: /app/my_dbt_project
      ENV: prod
      FILTER_DAYS_STOP_WORD: 3000
      HEALTHCHECK_SERVER: 0.0.0.0
      KEYWORDS_URL: https://keywords.mediatree.fr/api/v2/subtitle/
      LOGLEVEL: INFO
      MEDIATREE_AUTH_URL: https://keywords.mediatree.fr/api/auth/token/
      MEDIATREE_USER: quotaclimat
      MODIN_CPUS: 2
      MODIN_ENGINE: ray
      MODIN_MEMORY: 2000000000
      POSTGRES_DB: barometre
      POSTGRES_PORT: 17975
      RAY_COLOR_PREFIX: 1
      RAY_memory_monitor_refresh_ms: 0
      BUCKET: "{{ secret('SCW_ACCESS') }}"
      BUCKET_SECRET: "{{ secret('SCW_SECRET') }}"
      MEDIATREE_PASSWORD: "{{ secret('MEDIATREE_PASSWORD') }}"
      POSTGRES_USER: "{{ secret('POSTGRES_USER_DEV') }}"
      POSTGRES_HOST: "{{ secret('POSTGRES_HOST_DEV') }}"
      POSTGRES_PASSWORD: "{{ secret('POSTGRES_PASSWORD_DEV') }}"
      SENTRY_DSN: "{{ secret('SENTRY_DSN') }}"

  - id: detect_misinformation
    shmSize: 2gb
    type: io.kestra.plugin.docker.Run
    containerImage: "{{ envs.container_registry_misinformation }}:latest"
    pullPolicy: ALWAYS
    credentials:
      registry: "{{ envs.container_registry_misinformation }}"
      username: nologin
      password: "{{ secret('SCW_SECRET') }}"
    env: 
      APP_NAME: label-misinformation
      AWS_DEFAULT_REGION: fr-par
      BUCKET_INPUT: test-bucket-mediatree
      BUCKET_OUTPUT: test-bucket-mediatree
      BUCKET_OUTPUT_BELGIUM: test-bucket-mediatree
      BUCKET_OUTPUT_BRAZIL: test-bucket-mediatree
      BUCKET_OUTPUT_FOLDER: test-bucket-mediatree
      BUCKET_OUTPUT_GERMANY: test-bucket-mediatree
      COUNTRY: france
      ENV: production
      KEYWORDS_URL: https://keywords.mediatree.fr/api/v2/subtitle/
      LABEL_STUDIO_PROJECT: 6
      LABEL_STUDIO_PROJECT_BELGIUM: 17
      LABEL_STUDIO_PROJECT_BRAZIL: 9
      LABEL_STUDIO_PROJECT_GERMANY: 20
      LABEL_STUDIO_PROJECT_ID: 4
      LABEL_STUDIO_PROJECT_ID_BELGIUM: 12
      LABEL_STUDIO_PROJECT_ID_BRAZIL: 5
      LABEL_STUDIO_PROJECT_ID_GERMANY: 14
      LABEL_STUDIO_URL: https://barometre7kfudatm-labelstudio.functions.fnc.fr-par.scw.cloud
      LOGLEVEL: INFO
      MEDIATREE_AUTH_URL: https://keywords.mediatree.fr/api/auth/token/
      MEDIATREE_USER: quotaclimat
      MODEL_NAME: ft:gpt-4o-mini-2024-07-18:personal::B1xWiJRm
      MODEL_NAME_BRAZIL: ft:gpt-4o-mini-2024-07-18:personal::BJfrFQR1
      MODEL_NAME_GERMANY: ft:gpt-4o-mini-2024-07-18:personal::BWhlTPnX
      MODIN_MEMORY: 2000000000
      POSTGRES_DB: barometre
      POSTGRES_PORT: 17975
      RAY_COLOR_PREFIX: 1
      API_LABEL_STUDIO_KEY: "{{ secret('API_LABEL_STUDIO_KEY_DEV') }}"
      BUCKET_ACCESS: "{{ secret('SCW_ACCESS') }}"
      BUCKET_SECRET: "{{ secret('SCW_SECRET') }}"
      MEDIATREE_PASSWORD: "{{ secret('MEDIATREE_PASSWORD') }}"
      OPENAI_API_KEY: "{{ secret('OPENAI_API_KEY') }}"
      POSTGRES_HOST: "{{ secret('POSTGRES_HOST_DEV') }}"
      POSTGRES_PASSWORD: "{{ secret('POSTGRES_PASSWORD_DEV') }}"
      POSTGRES_USER: "{{ secret('POSTGRES_USER_DEV') }}"
      SENTRY_DSN: "{{ secret('SENTRY_DSN') }}"

  - id: dbt_run_transformations
    shmSize: 2gb
    type: io.kestra.plugin.docker.Run
    containerImage: "{{ envs.container_registry_barometre }}:latest"
    pullPolicy: ALWAYS
    credentials:
      registry: "{{ envs.container_registry_barometre }}"
      username: nologin
      password: "{{ secret('SCW_SECRET') }}"
    entryPoint:
      - ./entrypoints/dbt.sh
    env:
      DBT_PROFILES_DIR: /app/my_dbt_project/dbt
      DBT_PROJECT_DIR: /app/my_dbt_project
      LOGLEVEL: INFO
      MODIN_CPUS: 2
      MODIN_ENGINE: python
      MODIN_MEMORY: 2000000000
      POSTGRES_DB: barometre
      BUCKET: "{{ secret('SCW_ACCESS') }}"
      BUCKET_SECRET: "{{ secret('SCW_SECRET') }}"
      LABELSTUDIO_INGESTION_POSTGRES_USER: "{{ secret('POSTGRES_USER_DEV') }}"
      LABELSTUDIO_INGESTION_POSTGRES_PASSWORD: "{{ secret('POSTGRES_PASSWORD_DEV') }}"
      POSTGRES_USER: "{{ secret('POSTGRES_USER_DEV') }}"
      POSTGRES_HOST: "{{ secret('POSTGRES_HOST_DEV') }}"
      POSTGRES_PASSWORD: "{{ secret('POSTGRES_PASSWORD_DEV') }}"