# Based on experts' document
THEME_KEYWORDS = {
 "changement_climatique_constat" : [ # 1.1.2
    "climatique",
    "réchauffement de l’atmosphère",
    "réchauffement des océans",
    "réchauffement planétaire",
    "seuil de réchauffement",
    "écologique",
    "écologiste",
    "anthropocène",
    "cycle du carbone",
    "effet de serre",
    "neutralité carbone",
    "neutralité climatique",
    "croissance verte",
    "décarbonation",
    "empreinte carbone",
    "bilan carbone",
    "crédit carbone",
    "impact carbone",
    "soutenabilité environnementale",
    "développement durable",
    "dépolluer",
    "protection du vivant",
    "Protection de la planète",
    "conditions de vie sur Terre",
    "habitabilité de la planète",
    "protection des océans",
    "crise planétaire",
    "accord de paris",
    "COP21",
    "COP vingt-et-un",
    "COP15",
    "COP quinze",
    "COP26",
    "COP vingt-six",
    "COP27",
    "COP vingt-sept",
    "COP28",
    "COP vingt-huit",
    "COP29",
    "COP vingt-neuf",
    "COP30",
    "COP trente",
    "Conférence des Parties",
    "conférence climat",
    "conférence des Nations Unies sur le climat",
    "conférence des Nations Unies sur les changements climatiques",
    "GIEC",
    "Haut conseil pour le climat",
    "convention des nations unies sur le climat",
    "transition agricole",
    "transition énergétique",
]
,
"changement_climatique_causes_directes" : [ # 1.1.2.1
        "inaction climatique",
        "insuffisance climatique",
        "gaz à effet de serre",
        "polluant",
        "co2",
        "co deux",
        "dyoxide de carbone",
        "méthane",
        "émission de carbone",
        "émissions territoriales",
        "émissions importées",
        "émissions liées à la consommation",
        "émissions anthropiques",
        "énergies fossiles",
        "combustibles fossiles",
        "déforestation",
        "coupe rase",
        "greenwashing",
],
"changement_climatique_causes_indirectes": [ # 1.1.2.2
    "forage pétrolier",
    "puit de pétrole",
    "vache",
    "élevage",
    "élevage bovine",
    "viande",
    "malbouffe",
    "agricole",
    "agriculture",
    "agriculteur",
    "bâtiment",
    "Chauffage",
    "transport",
    "automobile",
    "voiture",
    "avion",
    "aviation",
    "SUV",
    "industrie",
    "secteur tertiaire",
    "énergie",
    "énergétique",
    "déchets",
    "carburant",
    "climatisation",
    "gaspillage alimentaire",
    "pétrole",
    "fuel",
    "fioul",
    "gaz",
    "gaz naturel",
    "charbon",
    "kérosène",
    "lignite",
    "essence",
    "diesel",
    "pompes à essence",
    "gaz de schiste",
    "gaz naturel liquifié",
    "or noir",
    "engrais azoté",
    "engrais de synthèse",
    "agriculture intensive",
    "élevage intensif",
    "agriculture industrielle",
    "agriculture conventionnelle",
    "serres chauffées",
    "agro-industriel",
    "chauffage au gaz",
    "chauffage au fuel",
    "passoire thermique",
    "passoire énergétique",
    "logement mal isolé",
    "îlot de chaleur",
],
"changement_climatique_consequences" : [ # 1.1.3
    "Augmentation des températures",
    "hausse de la température du globe",
    "élévation de la température",
    "élévation des températures",
    "climatique extrême",
    "période la plus chaude",
    "année la plus chaude",
    "mois le plus chaud",
    "jour le plus chaud",
    "record de température",
    "élévation du niveau de la mer",
    "hausse du niveau de la mer",
    "montée du niveau de la mer",
    "hausse du niveau marin",
    "élévation du niveau marin",
    "hausse du niveau des océans",
    "élévation du niveau des océans",
    "montée du niveau des océans",
    "montée des eaux",
    "fonte des glaces",
    "fonte des glaciers",
    "fonte de la banquise",
    "diminution de la banquise",
    "diminution des glaciers",
    "disparition des glaciers",
    "fonte des calottes glacières",
    "fonte du permafrost",
    "érosion côtière",
    "érosion des côtes",
    "inondation",
    "submersion",
    "submersion marine",
    "blanchissement des coraux",
    "sécheresse",
    "augmentation des risques de sécheresse",
    "stress hydrique",
    "canicule",
    "déficit de pluie",
    "pénurie de neige",
    "raréfaction de la ressource en eau",
    "rareté de la ressource en eau",
    "restrictions d’eau",
    "pénurie d'eau",
    "rareté saisonnière de la ressource en eau",
    "forte chaleur",
    "chaleur extrême",
    "vague de chaleur",
    "forte chaleur",
    "canicule marine",
    "salinisation des sols",
    "intensification du cycle de l’eau",
    "accès à l’eau",
    "acidification des oceans",
    "sécurité alimentaire",
    "perte agricole",
    "diminution des rendements agricoles",
    "baisse des rendements agricoles",
    "gel printanier",
    "tempête Xynthia",
    "La Roya",
    "disparition des coraux",
    "disparition des récifs coralliens",
    "acidification des océans",
    "météorologique extrême",
    "climatique extrême",
    "forte pluie",
    "pluie extrême",
    "pluie intense",
    "importante précipitation",
    "inondation exceptionnelle",
    "crue centennale",
    "cyclone",
    "Mortalité forestière",
    "disparition des forêts",
    "glissement de terrain",
    "maladaptation",
    "Pollution de l’air",
    "pollution atmosphérique",
    "pollution aux particules fines",
    "pollution à l’ozone",
    "migration climatique",
    "migrant climatique",
    "prolifération de moustiques",
    "moustique tigre",
    "chenille processionnaire",
    "zoonose",
    "espèce invasive",
    "retrait gonflement des argiles",
],
"attenuation_climatique_solutions_directes" : [ # 1.1.4.1
    "limiter la hausse des températures",
    "réduction des émissions de gaz à effet de serre",
    "baisse des émissions de gaz à effet de serre",
    "réduire les émissions de gaz à effet de serre",
    "diminuer les émissions de gaz à effet de serre",
    "réduction des émissions de carbone",
    "réduire les émissions de carbone",
    "diminuer les émissions de carbone",
    "baisse des émissions de carbone",
    "limiter les émissions de carbone",
    "contre les émissions de carbone",
    "sortie des énergies fossiles",
    "sortie du charbon",
    "décarbonation",
    "décarboner",
    "transition en dehors des énergies fossiles",
    "Atténuation du changement climatique",
    "moins polluant",
    "économie circulaire",
    "Mobilité durable",
    "Biocarburant",
    "écoconception",
    "Réseau de chaleur",
    "Réseaux de chaleur",
    "énergie renouvelable",
    "transition énergétique",
    "électricité décarboné",
    "énergie verte",
    "énergie durable",
    "éolien",
    # "panneaux solaires",
    "énergie solaire",
    "géothermie",
    "hydroélectricité",
    "centrale hydroélectrique",
    "biomasse",
    "méthaniseur",
    "méthanisation",
    "biogaz",
    "bois-énergie",
    "EPR",
    "hydrogène vert",
    "Économie d’énergie",
    "lutte contre le gaspillage énergétique",
    "réduction du gaspillage énergétique",
    "réduction des gaspillages énergétiques",
    "efficacité énergétique",
    "économiser de l’énergie",
    "sobriété énergétique",
    "végétalisation",
    "valorisation des déchets",
    "zéro plastique",
    "Ciment durable",
    "ciment de nouvelle génération",
    "zéro carbone",
    "béton bas carbone",
    "bas carbone",
    "captage et stockage",
    "capture et séquestration de carbone",
    "stocker le carbone",
    "capturer le carbone",
    "séquestration du carbone",
    "absorption du carbone",
    "quota de pêche",
    "stockage du carbone dans les sols",
    "réduction du cheptel",
    "agriculture de conservation",
    "restauration des tourbières",
    "protection des tourbières",
    "stockage du carbone dans les sols",
    "biochar",
    "restauration des zones humides",
    "lutte contre le gaspillage alimentaire",
    "réduction du gaspillage alimentaire",
    "antigaspi",
    "antigaspillage",
    "puits de carbone",
    "puits carbone",
    "sobriété",
    "consommation responsable",
    "consommation plus responsable",
    "écoresponsable",
    "reforestation",
    "ajustement carbone",
    "revégéltalisation",
]
,"attenuation_climatique_solutions_indirectes": [ # 	1.1.4.2
    "transition écologique"
    ,"industrie verte"
    ,"agroécologie"
    ,"agro écologie"
    ,"polyculture élevage"
    ,"agroforesterie"
    ,"développement durable"
    ,"alternative durable"
    ,"transition climatique"
    ,"planification écologique"
    ,"mutation écologique"
    ,"covoiturage"
    ,"nucléaire"
    ,"réacteur nucléaire"
    ,"vélos"
    ,"marche à pied"
    ,"Train"
    ,"transport maritime"
    ,"Transport collectif"
    ,"transport en commun"
    ,"Bus électrique"
    ,"Bus"
    ,"tramway"
    ,"éducation au changement climatique"
    ,"Bois d’oeuvre"
    ,"isolation"
    ,"isolation thermique"
    ,"Rénovation énergétique"
    ,"# pompes à chaleur"
    ,"changement de chaudière"
    ,"chaudière biomasse"
    ,"matériaux biosourcés"
    ,"matériaux recyclés"
    ,"matériaux recyclables"
    ,"forêt"
    ,"tri à la source"
    ,"biodégradable"
    ,"Recyclage"
    ,"compostage"
    ,"espace vert"
    ,"prairie"
    ,"Moins de viande"
    ,"végétarien"
    ,"végan"
    ,"agriculture bio "
    ,"agriculture durable"
    ,"Agriculture biologique"
    ,"permaculture"
    ,"label bio"
    ,"label écologique"
    ,"label éco "
    ,"label AB"
    ,"label HVE"
    ,"Camion électrique"
    ,"poid lourd électrique"
    ,"transport ferroviaire de marchandises"
    ,"fret ferroviaire"
    ,"transport fluvial de marchandises"
    ,"forêt mosaïque"
    ,"Baisse du trafic aérien"
    ,"zadisme"
    ,"zadiste"
    ,"zad"
    ,"Taxe carbone"
    ,"Décroissance"
    ,"manifestation pour le climat"
    ,"marche du siècle"
    ,"marche pour le climat"
    ,"activisme climatique"
    ,"activiste pour le climat"
    ,"militante écologiste"
    ,"désobéissance civile"
    ,"Voitures électriques"
]
,
"adaptation_climatique_solutions_directes": # 1.1.5.1
[
    "adaptation au changement climatique",
    "adaptation au dérèglement climatique",
    "adaptation au réchauffement climatique",
    "adaptation au réchauffement climatique",
    "adaptation climatique",
    "renforcer les digues",
    "renforcer les dunes",
    "gestion du littoral",
    "prévention des inondations",
    "limiter l’érosion des côtes",
    "lutter contre l’érosion",
    "gestion durable des forêts",
    "agroforesterie",
    "pêche durable",
    "aquaculture durable",
    "Gestion de la ressource en eau",
    "réduction de la demande en eau",
    "sauvegarde de la ressource en eau",
    "lutte contre le gaspillage d’eau",
    "économie d’eau",
    "réserve d’eau",
    "retenue collinaire",
    "gestion durable des terres cultivables",
    "Amélioration des pratiques d’élevages",
    "réduire l’élevage intensif",
    "restriction d’eau",
    "Réutilisation des eaux usées traitées",
    "Désalinisation des eaux",
    "îlots de fraîcheur",
    "revégétalisation",
    "renaturer",
    "reforestation",
    "résistant à la sécheresse",
    "prévention des catastrophes naturelles",
],
"adaptation_climatique_solutions_indirectes": # 1.1.5.2
[
    "Digue",
    "Dune",
    "mega bassine", 
    "barrage",
    "gestion des milieux aquatiques", 
    "sorgho",
    "Miscanthus",
],
"ressources_naturelles_concepts_generaux": # 1.2.1
[
    "crise environnementale",
    "crise climatique",
    "crise écologique",
    "impact environnementale",
    "anthropocène",
    "limites planétaires",
    "planète",
    "dépassement des limites planétaires",
    "épuisement des ressources",
    "jour du dépassement",
    "raréfaction de l’eau",
    "pénurie d’eau",
    "manque d’eau",
    "qualité de l’eau",
    "cycle de l’eau",
    "salinisation des nappes",
    "nappes phréatiques",
    "pollution de l’eau",
    "stress hydrique",
    "déficite de pluie",
    "pénurie de neige",
    "raréfaction de la ressource en eau",
    "rareté de la ressource en eau",
    "rareté saisonnière de la ressource en eau",
    "fortes chaleurs",   
    "chaleurs extrêmes",
    "vagues de chaleur",
    "salinisation des sols",
    "intensification du cycle de l’eau",
    "ressources minérales",
    "ressources renouvelables",
    "ressources naturelles",
    "terre rare",
    "lithium",
    "cobalt",
    "cuivre",
    "métaux critiques",
    "forêt",
    "gestion forestière",
    "bois d’oeuvre",
    "bois énergie",
    "artificialisation des sols",
    "mauvaise santé des sols",
    "appauvrissement des sols",
],
"ressources_naturelles_causes": # 1.2.2
[
    "surexploitation des ressources",
    "surexploitation",
    "surpêche",
    "polluant éternel",
    "PFAS",
    "substance chimique",
    "surconsommation",
    "pesticides",
    "produits toxiques",
    "déforestation",
    "gaspillage",
    "gisement", 
    "extraction",
    "sécheresse",
    "canicule",
],
"ressources_naturelles_solutions": # 1.2.3
[
    "Analyse de cycle de vie",
    "ACV",
    "biomimétisme",
    "bioinspiration",
    "sobriété",
    "réduction de la consommation",
    "maîtrise de la demande",
    "moins consommer",
    "fin de l'abondance",
    "Décroissance",
    "efficacité énergétique",
    "récupérateur d’eau",
    "stockage d’eau",
    "réemploi",
    "recyclage",
    "réparabilité",
    "repair cafés",
    "recycleries",
    "réutilisation des ressources",
    "ressources renouvelables",
    "lutte contre le gaspillage",
    "antigaspi",
    "santé des sols",
    "préservation des sols",
    "planification écologique",
    "transition écologique",
    "transformation écologique",
    "mutation écologique",
    "économie circulaire",
    "économie du réemploi",
    "malus écologique",
],
"biodiversite_concepts_generaux": # 1.3.1
[
    "Biodiversité",
    "diversité biologique",
    "diversité du vivant",
    "diversité des êtres vivants",
    "diversité génétique",
    "sixième extinction de masse",
    "disparition des espèces",
    "déclin du vivant",
    "conservation de la nature",
    "conserver la nature",
    "protéger la nature",
    "protection de la nature",
    "protéger le vivant",
    "protection du vivant",
    "écosystémique",
    "restauration des écosystèmes",
    "résilience des écosystèmes",
    "résilience des écosystèmes",
    "écosystèmes dégradés",
    "dégradation des écosystèmes",
    "IPBES",
    "Fertilité des sols",
    "pollinisation",
    "Intégrité écologique",
    "Convention des Nations unies sur la diversité biologique",
    "CDB",
    "COP biodiversité",
    "COP sur la biodiversité",
    "sommet sur la biodiversité",
    "COP de Montréal",
    "COP15",
    "COP 15",
    "COP quinze",
    "Union internationale pour la conservation de la nature",
    "UICN",
],
"biodiversite_causes_directes": # 1.3.2
[ 
    "polluant",
    "Dégradation de l'habitat",
    "condition dégradée d’habitation",
    "écosystème dégradé",
    "dégradation des écosystèmes",
    "destruction des habitats naturels",
    "destruction des milieux naturels",
    "Pression sur les milieux naturels",
    "perturbation des habitats",
    "perturbation des écosystèmes",
    "perte d’habitats",
    "Changement climatique",
    "Déforestation",
    "Acidification des océans",
    "acidification du milieu marin",
    "artificialisation des sols",
    "artificialisation des milieux naturels",
    "coupe rase",
],
 "biodiversite_causes_indirectes":
    [
    "Pesticide",
    "produit phytosanitaire",
    "glyphosate",
    "néonicotinoïde",
    "chlordécone",
    "herbicide",
    "fongicide",
    "intrants",
    "engrais azoté",
    "engrais phosphaté",
    "perturbateur endocrinien",
    "métaux lourds",
    "Pollution de l’air",
    "pollution de l’eau",
    "pollution des sols",
    "pollution chimique",
    "pollution environnementale",
    "pollution atmosphérique",
    "pollution plastique",
    "pêche industrielle",
    "agriculture industrielle",
    "agro-industrie",
    "agribusiness",
    "complexe agro-industriel",
    "agriculture intensive",
    "surpêche",
    "extractivisme",
    "extractiviste",
    "organisme génétiquement modifiée",
    "nouvelles techniques génomiques",
    "huile de palme",
    "tourisme de masse",
    "urbanisation",
    "l’étalement urbain",
    "surconsommation",
    "micro-plastiques",
    "changement d’usage des terres",
    "assèchement des zones humides",
    "disparition des haies",
    "braconnage",
    "trafic d’espèces",
    "commerce illégal d’espèces",
    "agricole",
    "agriculture",
    "agriculteur",
    "engrais azoté",
    "engrais de synthèse",
    "agriculture intensive",
    "élevage intensif",
    "agriculture industrielle",
    "agriculture conventionnelle",
    "agro-industriel",
],
"biodiversite_consequences": # 1.3.3
[
    "espèce menacée",
    "espèce menacée d’extinction",
    "crise d'extinction de masse",
    "espèce en voie de disparition",
    "corail",
    "coraux",
    "récif corallien",
    "récif de corail",
    "barrière de corail",
    "Liste rouge de l'UICN",
    "Liste rouge mondiale des espèces menacées",
    "disparition des oiseaux",
    "disparition des insectes",
    "disparition du vivant",
    "espèce invasive",
    "espèce envahissante",
    "migration des espèces",
    "bioérosion",
    "Zoonose",
    "zoonotique",
    "santé animale",
    "santé végétale",
  #  "propagation de maladies infectieuses",
    "propagation des espèces exotiques envahissantes",
    "prolifération des organismes nuisibles",
    "prolifération des maladies émergentes",
    "moustique tigre",
    "dengue",
    "perte de biodiversité des sols",
    "baisse du stockage du carbone dans les sols",
    "dégradation des puits de carbone",
    "dégradation des sols",
    "diminution des rendements des cultures",
    "perturbation du cycle de l’eau",
   # "Détérioration des conditions de santé",
    "acidification des oceans",
    "sécurité alimentaire",
    "perte agricole",
    "diminution des rendements agricoles",
    "baisse des rendements agricoles",
    "Mortalité forestière",
    "disparition des forêts",
],
"biodiversite_solutions_directes": # 1.3.4.1
[ 
    "moins polluant",
    "agroécologie",
    "agro écologie",
    "polyculture élevage",
    "agroforesterie",
    "agriculture de conservation",
    "protection des tourbières",
    "écoresponsable",
    "sobriété",
    "Solutions fondées sur la nature",
    "diversité génétique",
    "Protection du vivant",
    "réintroduction d'espèce",
    "préservation d'espèce",
    "préservation des milieux",
    "restauration des milieux",
    "restauration des écosystèmes",
    "restauration des forêts",
    "restauration de la biodiversité",
    "restaurer la biodiversité",
    "restauration des zones humides",
    "restauration des tourbières",
    "restaurer la qualité de l’air",
    "restaurer la qualité des sols",
    "reforestation",
    "revégétalisation",
    "renaturer",
    "protection des zones humides",
    "protection de la mangrove",
    "protection des zones côtières",
    "protection des côtes",
    "Corridor écologique",
    "végétalisation des espaces urbains",
    "végétalisation des villes",
    "réserve naturelle",
    "réserve de biosphère",
    "Agroforesterie",
    "agriculture biologique",
    "agriculture de conservation",
    "transition agroécologique",
    "pratiques agricoles durables",
    "espèces protégées",
    "protection des espèces",
    "protection de la barrière de corail",
    "protection des coraux",
    "protection du récif corallien",
    "restauration des coraux",
    "restauration du récif corallien",
    "aires protégées",
],
"biodiversite_solutions_indirectes": # 1.3.4.2
[ 
    "biochar",
    "planification écologique",
    "mutation écologique",
    "économie circulaire",
    "manger bio",
    "zéro artificialisation nette",
    "ZAN",
    "réserves naturelles",
    "droit de l’environnement",
    "infrastructures résilientes",
    "agricuture durable",
    "espace vert",
    "prairie",
    "agriculture bio",
    "Agriculture biologique",
    "permaculture",
    "forêt mosaïque",
    "décroissance",
    "militante écologiste",
    "gestion durable des forêts",
    "agroforesterie",
    "pêche durable",
    "aquaculture durable",
    "gestion des milieux aquatiques",
    "gestion durable des terres cultivables",
    "amélioration des pratiques d’élevages",
    "réduire l’élevage intensif",
    "résistant à la sécheresse",
]
}