# Based on advertising
STOP_WORDS = [
    "bonus écologique"
    ,"groupe verlaine isolation thermique"
    ,"haute isolation thermique fabriqué en france"
    ,"ou covoiturage tous les moyens sont bon"
    ,"blablacar et recevez cent euros de prime covoiturage"
    ,"conditions sébastien point fr covoiturage"
    ,"sur dacia point fr covoiturage"
    ,"dacia point fr un covoiturage"
    ,"engie peut vous aider par exemple avec des panneaux solaires"
    ,"panneaux solaires pour produire votre énergie"
    ,"panneaux solaires groupe"
    ,"verlaine installateur de panneaux photovoltaïques"
    ,"avec le leader du photovoltaïque"
    ,"en train d"
    ,"huile de coude est aussi une énergie renouvelable"
    ,"huile de coude était aussi une énergie renouvelable"
    ,'huile de coude étaient aussi une énergie renouvelable'
    ,"climatique c' est pour ça que je suis au crédit coopératif"
    ,"le mouvement de la rénovation énergétique"
    ,"installateur de pompe à chaleur air"
    ,"et plus durable et avec spoticar"
    ,"l' éolien jeanjean"
    ,"bd thierry rénovation énergétique point fr"
    ,"le mouvement de la rénovation énergétique"
    ,"en machine le gaspillage"
    ,"l' économie circulaire liddell"
    ,"l' économie circulaire carrefour"
    ,"pour l' économie circulaire bonjour"
    ,"sans ogm et cent pour cent"
    ,"nourries sans ogm"
    ,"nourries sans ogm et ogm cent"
    ,"Salon de jardin miami fabriqué avec quatre-vingts pour cent de matériaux recyclés"
    ,"l' entreprise de julie fabrique des meubles en matériaux recyclés"
    ,"jardin miami fabriqué avec quatre-vingts pour cent de matériaux recyclés"
    ,"trier ses déchets ça fait partie du jeu"
    ,"trier ses déchets même si ce n' est pas toujours évident"
    ,"voire règlement services déchets"
    ,"salon de jardin miami fabriqué avec quatre-vingts pour cent de matériaux recyclés"
    ,"l' entreprise de julie fabrique des meubles en matériaux recyclés"
    ,"jardin miami fabriqué avec quatre-vingts pour cent de matériaux recyclés"
]
