"""keywords: add channel_title


Revision ID: 055173743036
Revises: a0a707673259
Create Date: 2024-06-05 11:43:22.071610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055173743036'
down_revision: Union[str, None] = 'a0a707673259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keywords', sa.Column('channel_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keywords','channel_title')
    # ### end Alembic commands ###
