"""keywords: program name

Revision ID: 2c48f626a749
Revises: 
Create Date: 2024-04-12 12:44:23.512407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c48f626a749'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keywords', sa.Column('channel_program', sa.String(), nullable=True))
    op.add_column('keywords', sa.Column('channel_program_type', sa.String(), nullable=True))
    op.add_column('keywords', sa.Column('category', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keywords', 'category')
    op.drop_column('keywords', 'channel_program_type')
    op.drop_column('keywords', 'channel_program')
    # ### end Alembic commands ###
