"""program metadata

Revision ID: 30abfd828007
Revises: 43103d5b49c9
Create Date: 2024-10-03 14:18:09.874225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30abfd828007'
down_revision: Union[str, None] = '43103d5b49c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_metadata', sa.Column('program_grid_start', sa.DateTime(), nullable=True))
    op.add_column('program_metadata', sa.Column('program_grid_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_metadata', 'program_grid_end')
    op.drop_column('program_metadata', 'program_grid_start')
    # ### end Alembic commands ###
