"""program: add start/end date for grid evolution

Revision ID: 43103d5b49c9
Revises: af956a85658f
Create Date: 2024-10-02 13:18:56.251135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43103d5b49c9'
down_revision: Union[str, None] = 'af956a85658f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_metadata', sa.Column('program_grid_start', sa.String(), server_default='2023-04-01', nullable=False))
    op.add_column('channel_metadata', sa.Column('program_grid_end', sa.String(), server_default='', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_metadata', 'program_grid_end')
    op.drop_column('channel_metadata', 'program_grid_start')
    # ### end Alembic commands ###
