"""dictionary category

Revision ID: 44f13b7eebd4
Revises: 827fb6dde3bb
Create Date: 2025-05-23 12:54:53.323525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44f13b7eebd4'
down_revision: Union[str, None] = '827fb6dde3bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary', sa.Column('category', sa.String(), nullable=True))
    op.add_column('dictionary', sa.Column('theme', sa.String(), nullable=True))

    op.drop_column('dictionary', 'categories')
    op.drop_column('dictionary', 'themes')

    op.drop_column('dictionary', 'solution')
    op.drop_column('dictionary', 'consequence')
    op.drop_column('dictionary', 'cause')
    op.drop_column('dictionary', 'general_concepts')
    op.drop_column('dictionary', 'statement')

    op.drop_column('dictionary', 'crisis_climate')
    op.drop_column('dictionary', 'crisis_biodiversity')
    op.drop_column('dictionary', 'crisis_resource')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    op.add_column('dictionary', sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('dictionary', sa.Column('themes', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('dictionary', sa.Column('solution', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    op.add_column('dictionary', sa.Column('consequence', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    op.add_column('dictionary', sa.Column('cause', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    op.add_column('dictionary', sa.Column('general_concepts', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    op.add_column('dictionary', sa.Column('statement', sa.Boolean(), nullable=True, server_default=sa.text('false')))

    op.add_column('dictionary', sa.Column('crisis_climate', sa.Boolean(), nullable=True, server_default=sa.text('true')))
    op.add_column('dictionary', sa.Column('crisis_biodiversity', sa.Boolean(), nullable=True, server_default=sa.text('true')))
    op.add_column('dictionary', sa.Column('crisis_resource', sa.Boolean(), nullable=True, server_default=sa.text('true')))

    op.drop_column('dictionary', 'category')
    op.drop_column('dictionary', 'theme')