"""add 20/30

Revision ID: 4ccd746ee291
Revises: 2450da0e6c60
Create Date: 2024-06-20 06:35:00.316441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ccd746ee291'
down_revision: Union[str, None] = '2450da0e6c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('keywords', sa.Column('number_of_keywords_20', sa.Integer(), nullable=True))
    op.alter_column('keywords', sa.Column('number_of_keywords_30', sa.Integer(), nullable=True))
    op.alter_column('keywords', sa.Column('number_of_keywords_40', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keywords', 'number_of_keywords_20')
    op.drop_column('keywords', 'number_of_keywords_30')
    op.drop_column('keywords', 'number_of_keywords_40')
    # ### end Alembic commands ###
