"""add language to macro category

Revision ID: 5833799c8abc
Revises: a578d21d7aee
Create Date: 2026-03-13 09:44:30.531752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5833799c8abc'
down_revision: Union[str, None] = 'a578d21d7aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyword_macro_category', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keyword_macro_category','language')
    # ### end Alembic commands ###
