"""Add info/public to program metadata

Revision ID: 5bff4dceda53
Revises: c1d78b9968fe
Create Date: 2024-05-03 09:09:44.751432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bff4dceda53'
down_revision: Union[str, None] = 'c1d78b9968fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_metadata', sa.Column('public', sa.Boolean(), nullable=True))
    op.add_column('program_metadata', sa.Column('infocontinue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_metadata', 'infocontinue')
    op.drop_column('program_metadata', 'public')
    # ### end Alembic commands ###
