"""add 20/30

Revision ID: 5ccd746ee292
Revises: 4ccd746ee291
Create Date: 2024-07-03 06:35:00.316441
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ccd746ee292'
down_revision: Union[str, None] = '4ccd746ee291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keywords', sa.Column('updated_at',sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keywords', 'updated_at')
    # ### end Alembic commands ###
