"""Add radio to program metadata

Revision ID: a0a707673259
Revises: 5bff4dceda53
Create Date: 2024-05-03 09:36:04.954535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a707673259'
down_revision: Union[str, None] = '5bff4dceda53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_metadata', sa.Column('radio', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_metadata', 'radio')
    # ### end Alembic commands ###
