"""Add tables labelstudio

Revision ID: a578d21d7aee
Revises: 44f13b7eebd4
Create Date: 2025-10-09 14:18:14.410103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a578d21d7aee'
down_revision: Union[str, None] = '44f13b7eebd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labelstudio_task_aggregate',
    sa.Column('task_aggregate_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_labeled', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('overlap', sa.Integer(), nullable=False),
    sa.Column('file_upload_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('inner_id', sa.BigInteger(), nullable=True),
    sa.Column('total_annotations', sa.Integer(), nullable=False),
    sa.Column('cancelled_annotations', sa.Integer(), nullable=False),
    sa.Column('total_predictions', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('last_comment_updated_at', sa.DateTime(), nullable=True),
    sa.Column('unresolved_comment_count', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('task_aggregate_id')
    )
    op.create_table('labelstudio_task_completion_aggregate',
    sa.Column('task_completion_aggregate_id', sa.String(), nullable=False),
    sa.Column('task_aggregate_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('was_cancelled', sa.Boolean(), nullable=False),
    sa.Column('ground_truth', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('prediction', sa.JSON(), nullable=True),
    sa.Column('lead_time', sa.Double(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('parent_prediction_id', sa.Integer(), nullable=True),
    sa.Column('parent_annotation_id', sa.Integer(), nullable=True),
    sa.Column('last_action', sa.Text(), nullable=True),
    sa.Column('last_created_by_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('unique_id', sa.Uuid(), nullable=True),
    sa.Column('draft_created_at', sa.DateTime(), nullable=True),
    sa.Column('import_id', sa.BigInteger(), nullable=True),
    sa.Column('bulk_created', sa.Boolean(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['task_aggregate_id'], ['labelstudio_task_aggregate.task_aggregate_id'], ),
    sa.PrimaryKeyConstraint('task_completion_aggregate_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labelstudio_task_completion_aggregate')
    op.drop_table('labelstudio_task_aggregate')
    # ### end Alembic commands ###
