"""hrfp counters

Revision ID: ac96222af6fe
Revises: 30abfd828007
Create Date: 2024-12-02 14:36:21.970968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac96222af6fe'
down_revision: Union[str, None] = '30abfd828007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keywords', sa.Column('number_of_changement_climatique_constat_no_hrfp', sa.Integer(), nullable=True))
    op.add_column('keywords', sa.Column('number_of_changement_climatique_causes_no_hrfp', sa.Integer(), nullable=True))
    op.add_column('keywords', sa.Column('number_of_changement_climatique_consequences_no_hrfp', sa.Integer(), nullable=True))
    op.add_column('keywords', sa.Column('number_of_attenuation_climatique_solutions_no_hrfp', sa.Integer(), nullable=True))
    op.add_column('keywords', sa.Column('number_of_adaptation_climatique_solutions_no_hrfp', sa.Integer(), nullable=True))
    op.add_column('keywords', sa.Column('number_of_ressources_no_hrfp', sa.Integer(), nullable=True))
    op.add_column('keywords', sa.Column('number_of_ressources_solutions_no_hrfp', sa.Integer(), nullable=True))
    op.add_column('keywords', sa.Column('number_of_biodiversite_concepts_generaux_no_hrfp', sa.Integer(), nullable=True))
    op.add_column('keywords', sa.Column('number_of_biodiversite_causes_no_hrfp', sa.Integer(), nullable=True))
    op.add_column('keywords', sa.Column('number_of_biodiversite_consequences_no_hrfp', sa.Integer(), nullable=True))
    op.add_column('keywords', sa.Column('number_of_biodiversite_solutions_no_hrfp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keywords', 'number_of_biodiversite_solutions_no_hrfp')
    op.drop_column('keywords', 'number_of_biodiversite_consequences_no_hrfp')
    op.drop_column('keywords', 'number_of_biodiversite_causes_no_hrfp')
    op.drop_column('keywords', 'number_of_biodiversite_concepts_generaux_no_hrfp')
    op.drop_column('keywords', 'number_of_ressources_solutions_no_hrfp')
    op.drop_column('keywords', 'number_of_ressources_no_hrfp')
    op.drop_column('keywords', 'number_of_adaptation_climatique_solutions_no_hrfp')
    op.drop_column('keywords', 'number_of_attenuation_climatique_solutions_no_hrfp')
    op.drop_column('keywords', 'number_of_changement_climatique_consequences_no_hrfp')
    op.drop_column('keywords', 'number_of_changement_climatique_causes_no_hrfp')
    op.drop_column('keywords', 'number_of_changement_climatique_constat_no_hrfp')
    # ### end Alembic commands ###
