"""program: add created_at updated_at

Revision ID: c08231a9eb37
Revises: 4333bc46985d
Create Date: 2025-03-29 08:17:51.997077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08231a9eb37'
down_revision: Union[str, None] = '4333bc46985d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_metadata', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() at time zone 'utc')"), nullable=True))
    op.add_column('program_metadata', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_metadata', 'updated_at')
    op.drop_column('program_metadata', 'created_at')
    # ### end Alembic commands ###
