"""Add country

Revision ID: f6d16859e34b
Revises: c08231a9eb37
Create Date: 2025-04-14 14:30:44.395215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6d16859e34b'
down_revision: Union[str, None] = 'c08231a9eb37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary', sa.Column('keyword_english', sa.String(), nullable=True))
    op.add_column('dictionary', sa.Column('keyword_german', sa.String(), nullable=True))
    op.add_column('dictionary', sa.Column('keyword_spanish', sa.String(), nullable=True))
    op.add_column('dictionary', sa.Column('keyword_portuguese', sa.String(), nullable=True))
    op.add_column('dictionary', sa.Column('keyword_polish', sa.String(), nullable=True))
    op.add_column('dictionary', sa.Column('keyword_danish', sa.String(), nullable=True))
    op.add_column('dictionary', sa.Column('keyword_italian', sa.String(), nullable=True))
    op.add_column('dictionary', sa.Column('keyword_arabic', sa.String(), nullable=True))
    op.add_column('dictionary', sa.Column('keyword_greek', sa.String(), nullable=True))
    op.add_column('dictionary', sa.Column('keyword_dutch', sa.String(), nullable=True))
    op.add_column('dictionary', sa.Column('keyword_latvian', sa.String(), nullable=True))
    op.drop_column('dictionary', 'language')
    op.add_column('keywords', sa.Column('country', sa.Text(), nullable=True))


    op.add_column('program_metadata', sa.Column('country', sa.Text(), nullable=True))
    op.add_column('stop_word', sa.Column('country', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stop_word', 'country')
   
    op.drop_column('program_metadata', 'country')
    
    op.drop_column('keywords', 'country')
    op.add_column('dictionary', sa.Column('language', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('dictionary', 'keyword_latvian')
    op.drop_column('dictionary', 'keyword_dutch')
    op.drop_column('dictionary', 'keyword_greek')
    op.drop_column('dictionary', 'keyword_arabic')
    op.drop_column('dictionary', 'keyword_italian')
    op.drop_column('dictionary', 'keyword_danish')
    op.drop_column('dictionary', 'keyword_polish')
    op.drop_column('dictionary', 'keyword_portuguese')
    op.drop_column('dictionary', 'keyword_spanish')
    op.drop_column('dictionary', 'keyword_german')
    op.drop_column('dictionary', 'keyword_english')
    # ### end Alembic commands ###
