"""Add country

Revision ID: f6d16859e34b
Revises: c08231a9eb37
Create Date: 2025-04-14 14:30:44.395215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6d16859e34b'
down_revision: Union[str, None] = 'c08231a9eb37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary', sa.Column('language', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('keywords', sa.Column('country', sa.Text(), nullable=True))

    op.add_column('program_metadata', sa.Column('country', sa.Text(), nullable=True))
    op.add_column('stop_word', sa.Column('country', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stop_word', 'country')
   
    op.drop_column('program_metadata', 'country')
    
    op.drop_column('keywords', 'country')
    op.add_column('dictionary', sa.Column('language', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('dictionary', 'language')
    # ### end Alembic commands ###
