channels_programs_belgium = [
    {"channel_name": "vivacite", "start": "06:00", "end": "06:10", "weekday": "*", "program_name": "Flash Info 06:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vivacite", "start": "07:00", "end": "07:10", "weekday": "*", "program_name": "Flash Info 07:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vivacite", "start": "08:00", "end": "08:10", "weekday": "*", "program_name": "Flash Info 08:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vivacite", "start": "09:00", "end": "09:10", "weekday": "*", "program_name": "Flash Info 09:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vivacite", "start": "16:00", "end": "16:10", "weekday": "*", "program_name": "Flash Info 16:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vivacite", "start": "17:00", "end": "17:10", "weekday": "*", "program_name": "Flash Info 17:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vivacite", "start": "18:00", "end": "18:10", "weekday": "*", "program_name": "Flash Info 18:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vivacite", "start": "19:00", "end": "19:10", "weekday": "*", "program_name": "Flash Info 19:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},

    {"channel_name": "bel-rtl", "start": "06:00", "end": "06:10", "weekday": "*", "program_name": "Flash Info 06:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "bel-rtl", "start": "07:00", "end": "07:10", "weekday": "*", "program_name": "Flash Info 07:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "bel-rtl", "start": "08:00", "end": "08:10", "weekday": "*", "program_name": "Flash Info 08:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "bel-rtl", "start": "09:00", "end": "09:10", "weekday": "*", "program_name": "Flash Info 09:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "bel-rtl", "start": "16:00", "end": "16:10", "weekday": "weekday", "program_name": "Flash Info 16:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "bel-rtl", "start": "17:00", "end": "17:10", "weekday": "weekday", "program_name": "Flash Info 17:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "bel-rtl", "start": "18:00", "end": "18:10", "weekday": "weekday", "program_name": "Flash Info 18:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "bel-rtl", "start": "19:00", "end": "19:10", "weekday": "weekday", "program_name": "Flash Info 19:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "la-premiere", "start": "06:00", "end": "09:00", "weekday": "*", "program_name": "Matinales", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "la-premiere", "start": "12:00", "end": "13:00", "weekday": "*", "program_name": "12:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "la-premiere", "start": "17:00", "end": "19:00", "weekday": "weekday", "program_name": "17:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},

    {"channel_name": "ln-radio", "start": "06:00", "end": "06:10", "weekday": "*", "program_name": "Flash Info 06:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "06:30", "end": "06:40", "weekday": "*", "program_name": "Flash Info 06:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "07:00", "end": "07:10", "weekday": "*", "program_name": "Flash Info 07:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "07:30", "end": "07:40", "weekday": "*", "program_name": "Flash Info 07:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "08:00", "end": "08:10", "weekday": "*", "program_name": "Flash Info 08:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "08:30", "end": "08:40", "weekday": "*", "program_name": "Flash Info 08:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "09:00", "end": "09:10", "weekday": "*", "program_name": "Flash Info 09:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "09:30", "end": "09:40", "weekday": "*", "program_name": "Flash Info 09:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "12:00", "end": "12:10", "weekday": "*", "program_name": "Flash Info 12:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "12:30", "end": "12:40", "weekday": "*", "program_name": "Flash Info 12:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "13:00", "end": "13:10", "weekday": "*", "program_name": "Flash Info 13:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "13:30", "end": "13:40", "weekday": "*", "program_name": "Flash Info 13:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "14:00", "end": "14:10", "weekday": "*", "program_name": "Flash Info 14:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "14:30", "end": "14:40", "weekday": "*", "program_name": "Flash Info 14:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "16:00", "end": "16:10", "weekday": "*", "program_name": "Flash Info 16:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "16:30", "end": "16:40", "weekday": "*", "program_name": "Flash Info 16:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "17:00", "end": "17:10", "weekday": "*", "program_name": "Flash Info 17:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "17:30", "end": "17:40", "weekday": "*", "program_name": "Flash Info 17:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "18:00", "end": "18:10", "weekday": "*", "program_name": "Flash Info 18:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "18:30", "end": "18:40", "weekday": "*", "program_name": "Flash Info 18:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "19:00", "end": "19:10", "weekday": "*", "program_name": "Flash Info 19:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},

    {"channel_name": "radio-1", "start": "07:00", "end": "07:10", "weekday": "*", "program_name": "Het Journaal 07:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-1", "start": "08:00", "end": "08:10", "weekday": "*", "program_name": "Het Journaal 08:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-1", "start": "09:00", "end": "09:10", "weekday": "*", "program_name": "Het Journaal 09:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-1", "start": "10:00", "end": "10:10", "weekday": "*", "program_name": "Het Journaal 10:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-1", "start": "11:00", "end": "11:10", "weekday": "*", "program_name": "Het Journaal 11:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-1", "start": "06:00", "end": "09:00", "weekday": "*", "program_name": "De Ochtend", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-1", "start": "18:00", "end": "19:00", "weekday": "*", "program_name": "De Wereld Vand", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},

    {"channel_name": "radio-2", "start": "06:00", "end": "06:10", "weekday": "*", "program_name": "Flash Info 06:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-2", "start": "06:30", "end": "06:40", "weekday": "*", "program_name": "Flash Info 06:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-2", "start": "07:00", "end": "07:10", "weekday": "*", "program_name": "Flash Info 07:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-2", "start": "07:30", "end": "07:40", "weekday": "*", "program_name": "Flash Info 07:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-2", "start": "08:00", "end": "08:10", "weekday": "*", "program_name": "Flash Info 08:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-2", "start": "08:30", "end": "08:40", "weekday": "*", "program_name": "Flash Info 08:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-2", "start": "09:00", "end": "09:10", "weekday": "*", "program_name": "Flash Info 09:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-2", "start": "09:30", "end": "09:40", "weekday": "*", "program_name": "Flash Info 09:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-2", "start": "12:00", "end": "12:10", "weekday": "*", "program_name": "Flash Info 12:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-2", "start": "12:30", "end": "12:40", "weekday": "*", "program_name": "Flash Info 12:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-2", "start": "13:00", "end": "13:10", "weekday": "*", "program_name": "Flash Info 13:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-2", "start": "13:30", "end": "13:40", "weekday": "*", "program_name": "Flash Info 13:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-2", "start": "14:00", "end": "14:10", "weekday": "*", "program_name": "Flash Info 14:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-2", "start": "14:30", "end": "14:40", "weekday": "*", "program_name": "Flash Info 14:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-2", "start": "16:00", "end": "16:10", "weekday": "*", "program_name": "Flash Info 16:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-2", "start": "16:30", "end": "16:40", "weekday": "*", "program_name": "Flash Info 16:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-2", "start": "17:00", "end": "17:10", "weekday": "*", "program_name": "Flash Info 17:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-2", "start": "17:30", "end": "17:40", "weekday": "*", "program_name": "Flash Info 17:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-2", "start": "18:00", "end": "18:10", "weekday": "*", "program_name": "Flash Info 18:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-2", "start": "18:30", "end": "18:40", "weekday": "*", "program_name": "Flash Info 18:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-2", "start": "19:00", "end": "19:10", "weekday": "*", "program_name": "Flash Info 19:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},

    {"channel_name": "stu-bru", "start": "06:00", "end": "06:10", "weekday": "*", "program_name": "Flash Info 06:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "stu-bru", "start": "06:30", "end": "06:40", "weekday": "*", "program_name": "Flash Info 06:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "stu-bru", "start": "07:00", "end": "07:10", "weekday": "*", "program_name": "Flash Info 07:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "stu-bru", "start": "07:30", "end": "07:40", "weekday": "*", "program_name": "Flash Info 07:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "stu-bru", "start": "08:00", "end": "08:10", "weekday": "*", "program_name": "Flash Info 08:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "stu-bru", "start": "08:30", "end": "08:40", "weekday": "*", "program_name": "Flash Info 08:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "stu-bru", "start": "09:00", "end": "09:10", "weekday": "*", "program_name": "Flash Info 09:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "stu-bru", "start": "09:30", "end": "09:40", "weekday": "*", "program_name": "Flash Info 09:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "stu-bru", "start": "12:00", "end": "12:10", "weekday": "*", "program_name": "Flash Info 12:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "stu-bru", "start": "12:30", "end": "12:40", "weekday": "*", "program_name": "Flash Info 12:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "stu-bru", "start": "13:00", "end": "13:10", "weekday": "*", "program_name": "Flash Info 13:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "stu-bru", "start": "13:30", "end": "13:40", "weekday": "*", "program_name": "Flash Info 13:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "stu-bru", "start": "14:00", "end": "14:10", "weekday": "*", "program_name": "Flash Info 14:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "stu-bru", "start": "14:30", "end": "14:40", "weekday": "*", "program_name": "Flash Info 14:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "stu-bru", "start": "16:00", "end": "16:10", "weekday": "*", "program_name": "Flash Info 16:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "stu-bru", "start": "16:30", "end": "16:40", "weekday": "*", "program_name": "Flash Info 16:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "stu-bru", "start": "17:00", "end": "17:10", "weekday": "*", "program_name": "Flash Info 17:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "stu-bru", "start": "17:30", "end": "17:40", "weekday": "*", "program_name": "Flash Info 17:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "stu-bru", "start": "18:00", "end": "18:10", "weekday": "*", "program_name": "Flash Info 18:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "stu-bru", "start": "18:30", "end": "18:40", "weekday": "*", "program_name": "Flash Info 18:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "stu-bru", "start": "19:00", "end": "19:10", "weekday": "*", "program_name": "Flash Info 19:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},

    {"channel_name": "qmusic", "start": "06:00", "end": "06:10", "weekday": "*", "program_name": "Flash Info 06:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "qmusic", "start": "06:30", "end": "06:40", "weekday": "*", "program_name": "Flash Info 06:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "qmusic", "start": "07:00", "end": "07:10", "weekday": "*", "program_name": "Flash Info 07:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "qmusic", "start": "07:30", "end": "07:40", "weekday": "*", "program_name": "Flash Info 07:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "qmusic", "start": "08:00", "end": "08:10", "weekday": "*", "program_name": "Flash Info 08:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "qmusic", "start": "08:30", "end": "08:40", "weekday": "*", "program_name": "Flash Info 08:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "qmusic", "start": "09:00", "end": "09:10", "weekday": "*", "program_name": "Flash Info 09:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "qmusic", "start": "09:30", "end": "09:40", "weekday": "*", "program_name": "Flash Info 09:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "qmusic", "start": "12:00", "end": "12:10", "weekday": "*", "program_name": "Flash Info 12:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "qmusic", "start": "12:30", "end": "12:40", "weekday": "*", "program_name": "Flash Info 12:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "qmusic", "start": "13:00", "end": "13:10", "weekday": "*", "program_name": "Flash Info 13:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "qmusic", "start": "13:30", "end": "13:40", "weekday": "*", "program_name": "Flash Info 13:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "qmusic", "start": "14:00", "end": "14:10", "weekday": "*", "program_name": "Flash Info 14:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "qmusic", "start": "14:30", "end": "14:40", "weekday": "*", "program_name": "Flash Info 14:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "qmusic", "start": "16:00", "end": "16:10", "weekday": "*", "program_name": "Flash Info 16:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "qmusic", "start": "16:30", "end": "16:40", "weekday": "*", "program_name": "Flash Info 16:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "qmusic", "start": "17:00", "end": "17:10", "weekday": "*", "program_name": "Flash Info 17:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "qmusic", "start": "17:30", "end": "17:40", "weekday": "*", "program_name": "Flash Info 17:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "qmusic", "start": "18:00", "end": "18:10", "weekday": "*", "program_name": "Flash Info 18:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "qmusic", "start": "18:30", "end": "18:40", "weekday": "*", "program_name": "Flash Info 18:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "qmusic", "start": "19:00", "end": "19:10", "weekday": "*", "program_name": "Flash Info 19:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "vrt1", "start": "13:00", "end": "13:20", "weekday": "weekday", "program_name": "VRT NWS Journaal 13:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vrt1", "start": "18:00", "end": "18:25", "weekday": "weekday", "program_name": "VRT NWS Journaal 18:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vrt1", "start": "19:00", "end": "19:45", "weekday": "weekday", "program_name": "VRT NWS Journaal 19:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vrt1", "start": "22:30", "end": "22:50", "weekday": "weekday", "program_name": "VRT NWS Journaal 22:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vrt1", "start": "13:00", "end": "13:15", "weekday": "weekend", "program_name": "VRT NWS Journaal 13:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vrt1", "start": "19:00", "end": "19:35", "weekday": "weekend", "program_name": "VRT NWS Journaal 19:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vrt1", "start": "22:30", "end": "22:45", "weekday": "weekend", "program_name": "VRT NWS Journaal 22:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},

    {"channel_name": "canvas", "start": "20:00", "end": "20:30", "weekday": "weekday", "program_name": "Terzake", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "canvas", "start": "20:35", "end": "21:20", "weekday": "weekday", "program_name": "De Afspraak", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "vtm", "start": "19:00", "end": "19:30", "weekday": "weekday", "program_name": "VTM Daily News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vtm", "start": "19:00", "end": "19:25", "weekday": "weekend", "program_name": "VTM Daily News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "play", "start": "20:00", "end": "21:15", "weekday": "0", "program_name": "De Tafel van Gert", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "play", "start": "20:00", "end": "21:15", "weekday": "1", "program_name": "De Tafel van Gert", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "play", "start": "20:00", "end": "21:15", "weekday": "2", "program_name": "De Tafel van Gert", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "play", "start": "20:00", "end": "21:15", "weekday": "4", "program_name": "De Tafel van Gert", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
]
