channels_programs_belgium = [
    {"channel_name": "vivacite", "start": "06:00", "end": "06:10", "weekday": "*", "program_name": "Flash Info 06:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vivacite", "start": "07:00", "end": "07:10", "weekday": "*", "program_name": "Flash Info 07:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vivacite", "start": "08:00", "end": "08:10", "weekday": "*", "program_name": "Flash Info 08:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vivacite", "start": "09:00", "end": "09:10", "weekday": "*", "program_name": "Flash Info 09:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vivacite", "start": "16:00", "end": "16:10", "weekday": "*", "program_name": "Flash Info 16:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vivacite", "start": "17:00", "end": "17:10", "weekday": "*", "program_name": "Flash Info 17:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vivacite", "start": "18:00", "end": "18:10", "weekday": "*", "program_name": "Flash Info 18:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "vivacite", "start": "19:00", "end": "19:10", "weekday": "*", "program_name": "Flash Info 19:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},

    {"channel_name": "bel-rtl", "start": "06:00", "end": "06:10", "weekday": "*", "program_name": "Flash Info 06:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "bel-rtl", "start": "07:00", "end": "07:10", "weekday": "*", "program_name": "Flash Info 07:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "bel-rtl", "start": "08:00", "end": "08:10", "weekday": "*", "program_name": "Flash Info 08:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "bel-rtl", "start": "09:00", "end": "09:10", "weekday": "*", "program_name": "Flash Info 09:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "bel-rtl", "start": "16:00", "end": "16:10", "weekday": "weekday", "program_name": "Flash Info 16:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "bel-rtl", "start": "17:00", "end": "17:10", "weekday": "weekday", "program_name": "Flash Info 17:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "bel-rtl", "start": "18:00", "end": "18:10", "weekday": "weekday", "program_name": "Flash Info 18:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "bel-rtl", "start": "19:00", "end": "19:10", "weekday": "weekday", "program_name": "Flash Info 19:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "la-premiere", "start": "06:00", "end": "09:00", "weekday": "*", "program_name": "Matinales", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "la-premiere", "start": "12:00", "end": "13:00", "weekday": "*", "program_name": "12:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "la-premiere", "start": "17:00", "end": "19:00", "weekday": "weekday", "program_name": "17:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},

    {"channel_name": "ln-radio", "start": "06:00", "end": "06:10", "weekday": "*", "program_name": "Flash Info 06:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "06:30", "end": "06:40", "weekday": "*", "program_name": "Flash Info 06:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "07:00", "end": "07:10", "weekday": "*", "program_name": "Flash Info 07:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "07:30", "end": "07:40", "weekday": "*", "program_name": "Flash Info 07:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "08:00", "end": "08:10", "weekday": "*", "program_name": "Flash Info 08:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "08:30", "end": "08:40", "weekday": "*", "program_name": "Flash Info 08:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "09:00", "end": "09:10", "weekday": "*", "program_name": "Flash Info 09:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "09:30", "end": "09:40", "weekday": "*", "program_name": "Flash Info 09:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "12:00", "end": "12:10", "weekday": "*", "program_name": "Flash Info 12:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "12:30", "end": "12:40", "weekday": "*", "program_name": "Flash Info 12:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "13:00", "end": "13:10", "weekday": "*", "program_name": "Flash Info 13:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "13:30", "end": "13:40", "weekday": "*", "program_name": "Flash Info 13:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "14:00", "end": "14:10", "weekday": "*", "program_name": "Flash Info 14:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "14:30", "end": "14:40", "weekday": "*", "program_name": "Flash Info 14:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "16:00", "end": "16:10", "weekday": "*", "program_name": "Flash Info 16:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "16:30", "end": "16:40", "weekday": "*", "program_name": "Flash Info 16:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "17:00", "end": "17:10", "weekday": "*", "program_name": "Flash Info 17:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "17:30", "end": "17:40", "weekday": "*", "program_name": "Flash Info 17:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "18:00", "end": "18:10", "weekday": "*", "program_name": "Flash Info 18:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "18:30", "end": "18:40", "weekday": "*", "program_name": "Flash Info 18:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "ln-radio", "start": "19:00", "end": "19:10", "weekday": "*", "program_name": "Flash Info 19:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
]
