channels_programs_poland = [
    {"channel_name": "tvp", "start": "19:30", "end": "20:00", "weekday": "*", "program_name": "i9:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "polsat", "start": "18:50", "end": "19:20", "weekday": "*", "program_name": "Wydarzenia", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "tvn", "start": "19:00", "end": "19:30", "weekday": "*", "program_name": "Fatky", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "polskieradio", "start": "00:00", "end": "00:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "01:00", "end": "01:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "02:00", "end": "02:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "03:00", "end": "03:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "04:00", "end": "04:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "05:00", "end": "05:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "06:00", "end": "06:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "07:00", "end": "07:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "08:00", "end": "08:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "09:00", "end": "09:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "10:00", "end": "10:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "11:00", "end": "11:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "12:00", "end": "12:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "13:00", "end": "13:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "14:00", "end": "14:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "15:00", "end": "15:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "16:00", "end": "16:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "17:00", "end": "17:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "18:00", "end": "18:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "19:00", "end": "19:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "20:00", "end": "20:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "21:00", "end": "21:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "22:00", "end": "22:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "23:00", "end": "23:05", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},

    {"channel_name": "polskieradio", "start": "00:30", "end": "00:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "01:30", "end": "01:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "02:30", "end": "02:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "03:30", "end": "03:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "04:30", "end": "04:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "05:30", "end": "05:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "06:30", "end": "06:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "07:30", "end": "07:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "08:30", "end": "08:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "09:30", "end": "09:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "10:30", "end": "10:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "11:30", "end": "11:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "12:30", "end": "12:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "13:30", "end": "13:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "14:30", "end": "14:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "15:30", "end": "15:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "16:30", "end": "16:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "17:30", "end": "17:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "18:30", "end": "18:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "19:30", "end": "19:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "20:30", "end": "20:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "21:30", "end": "21:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "22:30", "end": "22:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskieradio", "start": "23:30", "end": "23:35", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "tokfm", "start": "16:00", "end": "16:30", "weekday": "weekday", "program_name": "TOK 360", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tokfm", "start": "16:35", "end": "17:00", "weekday": "weekday", "program_name": "TOK 360", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tokfm", "start": "18:00", "end": "18:20", "weekday": "weekday", "program_name": "TOK 360", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},

    {"channel_name": "radiozet", "start": "00:00", "end": "00:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "01:00", "end": "01:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "02:00", "end": "02:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "03:00", "end": "03:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "04:00", "end": "04:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "05:00", "end": "05:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "06:00", "end": "06:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "07:00", "end": "07:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "08:00", "end": "08:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "09:00", "end": "09:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "10:00", "end": "10:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "11:00", "end": "11:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "12:00", "end": "12:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "13:00", "end": "13:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "14:00", "end": "14:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "15:00", "end": "15:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "16:00", "end": "16:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "17:00", "end": "17:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "18:00", "end": "18:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "19:00", "end": "19:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "20:00", "end": "20:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "21:00", "end": "21:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "22:00", "end": "22:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radiozet", "start": "23:00", "end": "23:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},

    {"channel_name": "eska", "start": "06:00", "end": "06:10", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "07:00", "end": "07:10", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "08:00", "end": "08:10", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "09:00", "end": "09:10", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "10:00", "end": "10:10", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "11:00", "end": "11:10", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "12:00", "end": "12:10", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "13:00", "end": "13:10", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "14:00", "end": "14:10", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "15:00", "end": "15:10", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "16:00", "end": "16:10", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "17:00", "end": "17:10", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
]
