channels_programs_poland = [
    {"channel_name": "tvp", "start": "19:30", "end": "20:00", "weekday": "*", "program_name": "i9:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "polsat", "start": "18:50", "end": "19:20", "weekday": "*", "program_name": "Wydarzenia", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "tvn", "start": "19:00", "end": "19:30", "weekday": "*", "program_name": "Fatky", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "polskie-radio", "start": "00:00", "end": "00:05", "weekday": "*", "program_name": "Informacje 00:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "01:00", "end": "01:05", "weekday": "*", "program_name": "Informacje 01:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "02:00", "end": "02:05", "weekday": "*", "program_name": "Informacje 02:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "03:00", "end": "03:05", "weekday": "*", "program_name": "Informacje 03:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "04:00", "end": "04:05", "weekday": "*", "program_name": "Informacje 04:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "05:00", "end": "05:05", "weekday": "*", "program_name": "Informacje 05:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "06:00", "end": "06:05", "weekday": "*", "program_name": "Informacje 06:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "07:00", "end": "07:05", "weekday": "*", "program_name": "Informacje 07:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "08:00", "end": "08:05", "weekday": "*", "program_name": "Informacje 08:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "09:00", "end": "09:05", "weekday": "*", "program_name": "Informacje 09:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "10:00", "end": "10:05", "weekday": "*", "program_name": "Informacje 10:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "11:00", "end": "11:05", "weekday": "*", "program_name": "Informacje 11:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "12:00", "end": "12:05", "weekday": "*", "program_name": "Informacje 12:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "13:00", "end": "13:05", "weekday": "*", "program_name": "Informacje 13:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "14:00", "end": "14:05", "weekday": "*", "program_name": "Informacje 14:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "15:00", "end": "15:05", "weekday": "*", "program_name": "Informacje 15:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "16:00", "end": "16:05", "weekday": "*", "program_name": "Informacje 16:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "17:00", "end": "17:05", "weekday": "*", "program_name": "Informacje 17:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "18:00", "end": "18:05", "weekday": "*", "program_name": "Informacje 18:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "19:00", "end": "19:05", "weekday": "*", "program_name": "Informacje 19:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "20:00", "end": "20:05", "weekday": "*", "program_name": "Informacje 20:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "21:00", "end": "21:05", "weekday": "*", "program_name": "Informacje 21:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "22:00", "end": "22:05", "weekday": "*", "program_name": "Informacje 22:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "23:00", "end": "23:05", "weekday": "*", "program_name": "Informacje 23:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},

    {"channel_name": "polskie-radio", "start": "00:30", "end": "00:35", "weekday": "*", "program_name": "Informacje 00:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "01:30", "end": "01:35", "weekday": "*", "program_name": "Informacje 01:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "02:30", "end": "02:35", "weekday": "*", "program_name": "Informacje 02:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "03:30", "end": "03:35", "weekday": "*", "program_name": "Informacje 03:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "04:30", "end": "04:35", "weekday": "*", "program_name": "Informacje 04:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "05:30", "end": "05:35", "weekday": "*", "program_name": "Informacje 05:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "06:30", "end": "06:35", "weekday": "*", "program_name": "Informacje 06:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "07:30", "end": "07:35", "weekday": "*", "program_name": "Informacje 07:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "08:30", "end": "08:35", "weekday": "*", "program_name": "Informacje 08:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "09:30", "end": "09:35", "weekday": "*", "program_name": "Informacje 09:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "10:30", "end": "10:35", "weekday": "*", "program_name": "Informacje 10:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "11:30", "end": "11:35", "weekday": "*", "program_name": "Informacje 11:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "12:30", "end": "12:35", "weekday": "*", "program_name": "Informacje 12:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "13:30", "end": "13:35", "weekday": "*", "program_name": "Informacje 13:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "14:30", "end": "14:35", "weekday": "*", "program_name": "Informacje 14:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "15:30", "end": "15:35", "weekday": "*", "program_name": "Informacje 15:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "16:30", "end": "16:35", "weekday": "*", "program_name": "Informacje 16:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "17:30", "end": "17:35", "weekday": "*", "program_name": "Informacje 17:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "18:30", "end": "18:35", "weekday": "*", "program_name": "Informacje 18:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "19:30", "end": "19:35", "weekday": "*", "program_name": "Informacje 19:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "20:30", "end": "20:35", "weekday": "*", "program_name": "Informacje 20:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "21:30", "end": "21:35", "weekday": "*", "program_name": "Informacje 21:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "22:30", "end": "22:35", "weekday": "*", "program_name": "Informacje 22:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "polskie-radio", "start": "23:30", "end": "23:35", "weekday": "*", "program_name": "", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "tokfm", "start": "16:00", "end": "16:30", "weekday": "weekday", "program_name": "TOK 360 16:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tokfm", "start": "16:35", "end": "17:00", "weekday": "weekday", "program_name": "TOK 360 16:35", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tokfm", "start": "18:00", "end": "18:20", "weekday": "weekday", "program_name": "TOK 360", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},

    {"channel_name": "radio-zet", "start": "00:00", "end": "00:10", "weekday": "*", "program_name": "Radio Zet News 00:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "01:00", "end": "01:10", "weekday": "*", "program_name": "Radio Zet News 01:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "02:00", "end": "02:10", "weekday": "*", "program_name": "Radio Zet News 02:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "03:00", "end": "03:10", "weekday": "*", "program_name": "Radio Zet News 03:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "04:00", "end": "04:10", "weekday": "*", "program_name": "Radio Zet News 04:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "05:00", "end": "05:10", "weekday": "*", "program_name": "Radio Zet News 05:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "06:00", "end": "06:10", "weekday": "*", "program_name": "Radio Zet News 06:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "07:00", "end": "07:10", "weekday": "*", "program_name": "Radio Zet News 07:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "08:00", "end": "08:10", "weekday": "*", "program_name": "Radio Zet News 08:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "09:00", "end": "09:10", "weekday": "*", "program_name": "Radio Zet News 09:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "10:00", "end": "10:10", "weekday": "*", "program_name": "Radio Zet News 10:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "11:00", "end": "11:10", "weekday": "*", "program_name": "Radio Zet News 11:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "12:00", "end": "12:10", "weekday": "*", "program_name": "Radio Zet News 12:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "13:00", "end": "13:10", "weekday": "*", "program_name": "Radio Zet News 13:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "14:00", "end": "14:10", "weekday": "*", "program_name": "Radio Zet News 14:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "15:00", "end": "15:10", "weekday": "*", "program_name": "Radio Zet News 15:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "16:00", "end": "16:10", "weekday": "*", "program_name": "Radio Zet News 16:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "17:00", "end": "17:10", "weekday": "*", "program_name": "Radio Zet News 17:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "18:00", "end": "18:10", "weekday": "*", "program_name": "Radio Zet News 18:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "19:00", "end": "19:10", "weekday": "*", "program_name": "Radio Zet News 19:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "20:00", "end": "20:10", "weekday": "*", "program_name": "Radio Zet News 20:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "21:00", "end": "21:10", "weekday": "*", "program_name": "Radio Zet News 21:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "22:00", "end": "22:10", "weekday": "*", "program_name": "Radio Zet News 22:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-zet", "start": "23:00", "end": "23:10", "weekday": "*", "program_name": "Radio Zet News", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},

    {"channel_name": "eska", "start": "06:00", "end": "06:10", "weekday": "*", "program_name": "Informacje 06:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "07:00", "end": "07:10", "weekday": "*", "program_name": "Informacje 07:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "08:00", "end": "08:10", "weekday": "*", "program_name": "Informacje 08:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "09:00", "end": "09:10", "weekday": "*", "program_name": "Informacje 09:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "10:00", "end": "10:10", "weekday": "*", "program_name": "Informacje 10:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "11:00", "end": "11:10", "weekday": "*", "program_name": "Informacje 11:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "12:00", "end": "12:10", "weekday": "*", "program_name": "Informacje 12:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "13:00", "end": "13:10", "weekday": "*", "program_name": "Informacje 13:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "14:00", "end": "14:10", "weekday": "*", "program_name": "Informacje 14:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "15:00", "end": "15:10", "weekday": "*", "program_name": "Informacje 15:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "16:00", "end": "16:10", "weekday": "*", "program_name": "Informacje 16:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "eska", "start": "17:00", "end": "17:10", "weekday": "*", "program_name": "Informacje", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "tv-republika", "start": "06:00", "end": "06:05", "weekday": "weekday", "program_name": "Agro Info", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tv-republika", "start": "12:30", "end": "12:45", "weekday": "weekday", "program_name": "Republika Dzien 12:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tv-republika", "start": "13:30", "end": "13:40", "weekday": "weekday", "program_name": "Republika Dzien 13:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tv-republika", "start": "14:00", "end": "14:10", "weekday": "weekday", "program_name": "Republika Dzien 14:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tv-republika", "start": "15:00", "end": "15:15", "weekday": "weekday", "program_name": "Republika Dzien 15:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tv-republika", "start": "16:00", "end": "16:15", "weekday": "weekday", "program_name": "Republika Dzien 16:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "tv-republika", "start": "14:00", "end": "14:10", "weekday": "5", "program_name": "Republika Dzien 14:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tv-republika", "start": "16:00", "end": "16:15", "weekday": "5", "program_name": "Republika Dzien 16:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "tv-republika", "start": "14:55", "end": "15:00", "weekday": "6", "program_name": "Republika Dzien 14:55", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tv-republika", "start": "16:00", "end": "16:15", "weekday": "6", "program_name": "Republika Dzien 16:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tv-republika", "start": "18:00", "end": "18:15", "weekday": "6", "program_name": "Republika Dzien 18:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "tv-republika", "start": "16:55", "end": "17:10", "weekday": "*", "program_name": "Express Republiki", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "tv-republika", "start": "19:00", "end": "20:20", "weekday": "weekday", "program_name": "Dzisiaj", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tv-republika", "start": "19:00", "end": "20:20", "weekday": "5", "program_name": "Dzisiaj", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tv-republika", "start": "19:00", "end": "20:00", "weekday": "6", "program_name": "Dzisiaj", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},

    {"channel_name": "tv-trwam", "start": "00:10", "end": "00:30", "weekday": "weekday", "program_name": "Informacje Dnia 00:10", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tv-trwam", "start": "03:00", "end": "03:20", "weekday": "weekday", "program_name": "Informacje Dnia 03:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tv-trwam", "start": "04:20", "end": "04:40", "weekday": "weekday", "program_name": "Informacje Dnia 04:20", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tv-trwam", "start": "08:00", "end": "08:15", "weekday": "weekday", "program_name": "Informacje Dnia 08:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tv-trwam", "start": "10:00", "end": "10:15", "weekday": "weekday", "program_name": "Informacje Dnia 10:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tv-trwam", "start": "12:03", "end": "12:20", "weekday": "weekday", "program_name": "Informacje Dnia 12:03", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tv-trwam", "start": "16:00", "end": "16:10", "weekday": "weekday", "program_name": "Informacje Dnia 16:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tv-trwam", "start": "18:05", "end": "18:15", "weekday": "weekday", "program_name": "Informacje Dnia 18:05", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tv-trwam", "start": "20:00", "end": "20:20", "weekday": "weekday", "program_name": "Informacje Dnia 20:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tv-trwam", "start": "21:20", "end": "21:40", "weekday": "weekday", "program_name": "Informacje Dnia 22:20", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "radio-maryja", "start": "04:10", "end": "05:10", "weekday": "weekday", "program_name": "Aktualnosci Dnia 04:10", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-maryja", "start": "13:10", "end": "14:00", "weekday": "weekday", "program_name": "Aktualnosci Dnia 13:10", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-maryja", "start": "16:00", "end": "16:15", "weekday": "weekday", "program_name": "Aktualnosci Dnia 16:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "radio-maryja", "start": "06:03", "end": "06:10", "weekday": "weekday", "program_name": "Serwis Informacjny 06:03", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-maryja", "start": "08:00", "end": "08:10", "weekday": "weekday", "program_name": "Serwis Informacjny 08:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-maryja", "start": "10:00", "end": "10:05", "weekday": "weekday", "program_name": "Serwis Informacjny 10:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-maryja", "start": "11:00", "end": "11:10", "weekday": "weekday", "program_name": "Serwis Informacjny 11:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-maryja", "start": "12:03", "end": "12:10", "weekday": "weekday", "program_name": "Serwis Informacjny 12:03", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-maryja", "start": "13:00", "end": "13:10", "weekday": "weekday", "program_name": "Serwis Informacjny 13:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-maryja", "start": "14:00", "end": "14:10", "weekday": "weekday", "program_name": "Serwis Informacjny 14:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-maryja", "start": "17:00", "end": "17:10", "weekday": "weekday", "program_name": "Serwis Informacjny 17:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-maryja", "start": "20:00", "end": "20:20", "weekday": "weekday", "program_name": "Serwis Informacjny 20:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "radio-maryja", "start": "23:00", "end": "23:59", "weekday": "weekday", "program_name": "Serwis Informacjny 23:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "radio-maryja", "start": "07:50", "end": "08:00", "weekday": "weekday", "program_name": "Feleiton Sprobuj pomyslec", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "radio-maryja", "start": "21:30", "end": "23:35", "weekday": "weekday", "program_name": "Rozmowy niedokonczone: Polityka w Polsce i wobec Polski", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "wpolsce24", "start": "01:30", "end": "01:45", "weekday": "weekday", "program_name": "Tele-Ekspres 01:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "wpolsce24", "start": "16:45", "end": "17:05", "weekday": "weekday", "program_name": "Tele-Ekspres 16:45", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "wpolsce24", "start": "01:30", "end": "01:45", "weekday": "5", "program_name": "Tele-Ekspres 01:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "wpolsce24", "start": "16:45", "end": "17:05", "weekday": "5", "program_name": "Tele-Ekspres 16:45", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},

    {"channel_name": "wpolsce24", "start": "06:00", "end": "06:30", "weekday": "weekday", "program_name": "Wiadomosci Poranne", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "wpolsce24", "start": "06:00", "end": "06:50", "weekday": "weekend", "program_name": "Wiadomosci Poranne", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "wpolsce24", "start": "00:00", "end": "00:25", "weekday": "weekday", "program_name": "Wiadomosci 00:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "wpolsce24", "start": "07:00", "end": "07:10", "weekday": "weekday", "program_name": "Wiadomosci 07:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "wpolsce24", "start": "08:00", "end": "08:05", "weekday": "weekday", "program_name": "Wiadomosci 08:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "wpolsce24", "start": "09:00", "end": "09:05", "weekday": "weekday", "program_name": "Wiadomosci 09:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "wpolsce24", "start": "19:30", "end": "20:00", "weekday": "weekday", "program_name": "Wiadomosci 19:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "wpolsce24", "start": "23:45", "end": "23:59", "weekday": "weekday", "program_name": "Wiadomosci 23:45", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "wpolsce24", "start": "07:30", "end": "07:35", "weekday": "weekday", "program_name": "Wiadomosci Agro", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "wpolsce24", "start": "09:30", "end": "09:35", "weekday": "weekday", "program_name": "Wiadomosci Gospodarka", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "wpolsce24", "start": "10:00", "end": "11:50", "weekday": "weekday", "program_name": "Kontra", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "wpolsce24", "start": "12:00", "end": "13:00", "weekday": "weekday", "program_name": "Rapport Wiadomosci 12:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "wpolsce24", "start": "15:00", "end": "16:00", "weekday": "weekday", "program_name": "Rapport Wiadomosci 15:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},

    {"channel_name": "wpolsce24", "start": "13:00", "end": "13:25", "weekday": "weekday", "program_name": "Piatka Pereiri", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},

    {"channel_name": "wpolsce24", "start": "13:25", "end": "13:50", "weekday": "weekday", "program_name": "Piatka Pochwata", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "wpolsce24", "start": "20:05", "end": "20:50", "weekday": "weekday", "program_name": "Minela 20:05 (Marek Pyza)", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "wpolsce24", "start": "20:50", "end": "21:40", "weekday": "weekday", "program_name": "Minela 20:05 (Magdalena Ogorek)", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "wpolsce24", "start": "19:30", "end": "20:00", "weekday": "5", "program_name": "Wiadomosci 19:30", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "wpolsce24", "start": "07:00", "end": "07:05", "weekday": "5", "program_name": "Wiadomosci Flash 07:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "wpolsce24", "start": "08:00", "end": "08:05", "weekday": "5", "program_name": "Wiadomosci Flash 08:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "wpolsce24", "start": "09:00", "end": "09:05", "weekday": "5", "program_name": "Wiadomosci Flash 09:00", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "wpolsce24", "start": "13:55", "end": "14:05", "weekday": "5", "program_name": "Wiadomosci Flash 13:55", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "wpolsce24", "start": "10:30", "end": "11:50", "weekday": "5", "program_name": "Ostra Szpila", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "tvs", "start": "10:00", "end": "10:05", "weekday": "0", "program_name": "Dzisiaj w regionie", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tvs", "start": "10:00", "end": "10:05", "weekday": "1", "program_name": "Dzisiaj w regionie", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tvs", "start": "10:00", "end": "10:05", "weekday": "2", "program_name": "Dzisiaj w regionie", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tvs", "start": "10:00", "end": "10:05", "weekday": "3", "program_name": "Dzisiaj w regionie", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tvs", "start": "10:08", "end": "10:13", "weekday": "4", "program_name": "Dzisiaj w regionie", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    
    {"channel_name": "tvs", "start": "11:35", "end": "11:40", "weekday": "0", "program_name": "Dzisiaj w regionie", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tvs", "start": "11:35", "end": "11:40", "weekday": "1", "program_name": "Dzisiaj w regionie", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tvs", "start": "11:35", "end": "11:40", "weekday": "2", "program_name": "Dzisiaj w regionie", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tvs", "start": "11:35", "end": "11:40", "weekday": "3", "program_name": "Dzisiaj w regionie", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
    {"channel_name": "tvs", "start": "11:10", "end": "11:15", "weekday": "4", "program_name": "Dzisiaj w regionie", "program_type": "","program_grid_start": "2023-04-01", "program_grid_end": "",},
]

