TOP_25_CHANNELS = [
    "TF1",
    "France 2",
    "France 3",
    "Canal+",
    "France 5",
    "M6",
    "BFMTV",
    "CNEWS",
    "LCI",
    "Arte",
    "Europe 1",
    "RMC",
    "RTL",
    "France Inter",
    "Euronews",
    "LCP",
    "France Info",
    "France 24",
    "France S",
    "TV5Monde",
    "BFM Business Radio",
    "BFM Business",
    "France Culture",
    "Radio Classique",
    "RFI",
]

TOP_CHANNELS_TV_8 = [
    "TF1",
    "France 2",
    "France 3",
    "Canal+",
    "France 5",
    "M6",
    "BFMTV",
    "CNEWS",
]

TOP_CHANNELS_TV = [
    "TF1",
    "France 2",
    "France 3",
    "Canal+",
    "France 5",
    "M6",
    "Arte",
    "C8",
    "France 24",
    "Euronews",
    "W9",
    "TMC",
    "TFX",
    "NRJ 12",
    "LCP",
    "LCI",
    "BFMTV",
    "BFM Business" "CNEWS",
    "CSTAR",
    "Gulli",
    "6ter",
    "RMC Découverte",
]

TOP_CHANNELS_RADIO = [
    "RFI",
    "France Inter",
    "RMC",
    "France Info",
    "RTL",
    "NRJ",
    "Nostalgie",
    "FIP",
    "France Culture",
    "Skyrock",
    "Chérie FM",
    "RTL2",
    "Fun Radio",
    "Radio Classique",
    "Rire et Chansons",
    "Sud Radio",
    "Nova",
    "France Musique",
    "OÜI FM",
    "BFM Business Radio",
    "Latina",
    "Le Mouv",
    "Guadeloupe 1ère",
    "Radio FG",
    "TSF Jazz",
]

TOP_CHANNELS_TV_CONTINU = ["LCP", "BFMTV", "CNEWS", "LCI", "France 24", "France Info:"]

TOP_CHANNELS_TV_GENERALISTE = [
    "TF1",
    "France 2",
    "France 3",
    "Canal+",
    "France 5",
    "M6",
    "C8",
    "W9",
    "TMC",
    "TFX",
    "NRJ 12",
    "CultureBox",
    "Gulli",
    "TF1 HD",
    "L'Équipe 21",
    "6ter",
    "RMC Story",
    "RMC Découverte",
    "Chérie 25",
]
