CLIMATE_KW = [
    "planète",
    "environnement",
    "crise-climatique",
    "climatique",
    "climat",
    "énergie",
    "gaz",
    " cop27",
    "  cop ",
    "climatique",
    "écologie",
    "CO2",
    "effet de serre",
    "transition énergetique",
    "carbone",
    "sécheresse",
    "methane",
    "GIEC",
    "zéro émission",
    "réchauffement",
    "changement climatique",
    "réchauffement de la planete",
    "réchauffement climatique",
    "réchauffement climatique anthropique",
    "risque climatique",
    "impact climatique",
    "Empreinte carbone",
    "Budget énergétique",
]
