# Liste des mots clés à rechercher et compter

CLIMATE_KW = [
    "planète",
    "environnement",
    "crise-climatique",
    "climatique",
    "climat",
    "énergie",
    "gaz",
    " cop27",
    "  cop ",
    "climatique",
    "écologie",
    "CO2",
    "effet de serre",
    "transition énergetique",
    "carbone",
    "sécheresse",
    "methane",
    "GIEC",
    "zéro émission",
    "réchauffement",
    "changement climatique",
    "réchauffement de la planete",
    "réchauffement climatique",
    "réchauffement climatique anthropique",
    "risque climatique",
    "impact climatique",
    "Empreinte carbone",
    "Budget énergétique",
    "énergies renouvelables",
]

politique_KW = [
    "élections municipales",
    "législatives",
    "présidentielle",
    "voter",
    "retraite",
    "droit",
    "vote",
    "premier ministre",
    "président",
    "Emmanuel Macron",
    "président de la république",
    "loi",
    "contre",
    "manifestations",
    "La mairie",
    "le maire",
    "débats à l’assemblée national",
    "débat",
    "réforme",
    "Institutions",
    "étranger",
    "Ukraine",
]
