---
- name: restart sshd
  systemd:
    name: sshd
    state: restarted

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: restart docker
  systemd:
    name: docker
    state: restarted
