version: 2

models:
  - name: homepage_environment_by_media_by_month
    description: "Aggregated environmental data with monthly averages"
    columns:
      - name: start
        description: "Month/Year"
        tests:
          - not_null

      - name: avg
        description: "Average environmental percentage"
        tests:
          - not_null

      - name: channel_title
        description: "Channel_Title"
        tests:
          - not_null


  - name: core_query_environmental_shares
    description: >
      Environmental shares data pulled from core_query_environmental_shares, 
      including climate and biodiversity metrics by program/channel.
    columns:
      - name: start
        description: Start date or timestamp of the observation.
      - name: channel_title
        description: 'Original: Program Metadata - Channel Name__channel_title'
      - name: public
        description: 'Original: Program Metadata - Channel Name__public'
      - name: infocontinue
        description: 'Original: Program Metadata - Channel Name__infocontinue'
      - name: radio
        description: 'Original: Program Metadata - Channel Name__radio'
      - name: environnement_total_pct
        description: 'Original: % environnement total'
      - name: climat_pct
        description: 'Original: % climat'
      - name: climat_cause_pct
        description: 'Original: % climat cause'
      - name: climat_solutions_adaptation_pct
        description: 'Original: % climat solutions adaptation '
      - name: climat_consequences_pct
        description: 'Original: % climat consequences'
      - name: climat_solutions_attenuation_pct
        description: 'Original: % climat solutions attenuation'
      - name: climat_constat_pct
        description: 'Original: % climat constat'
      - name: biodiversite_pct
        description: 'Original: % biodiversite'
      - name: biodiversite_constat_pct
        description: 'Original: % biodiversité constat'
      - name: biodiversite_solutions_pct
        description: 'Original: % biodiversité solutions'
      - name: biodiversite_consequences_pct
        description: 'Original: % biodiversité conséquences'
      - name: biodiversite_causes_pct
        description: 'Original: % biodiversité causes'
      - name: ressources_pct
        description: 'Original: % ressources'
      - name: ressources_constat_pct
        description: 'Original: % ressources constat'
      - name: ressources_solutions_pct
        description: 'Original: % ressources solutions'

  - name: core_query_environmental_shares_i8n
    description: >
      International Environmental shares data pulled from core_query_environmental_shares, 
      including climate and biodiversity metrics by program/channel.
    columns:
      - name: start
        description: Start date or timestamp of the observation.
      - name: channel_title
        description: 'Original: Program Metadata - Channel Name__channel_title'
      - name: public
        description: 'Original: Program Metadata - Channel Name__public'
      - name: infocontinue
        description: 'Original: Program Metadata - Channel Name__infocontinue'
      - name: radio
        description: 'Original: Program Metadata - Channel Name__radio'
      - name: environnement_total_pct
        description: 'Original: % environnement total'
      - name: climat_pct
        description: 'Original: % climat'
      - name: climat_cause_pct
        description: 'Original: % climat cause'
      - name: climat_solutions_adaptation_pct
        description: 'Original: % climat solutions adaptation '
      - name: climat_consequences_pct
        description: 'Original: % climat consequences'
      - name: climat_solutions_attenuation_pct
        description: 'Original: % climat solutions attenuation'
      - name: climat_constat_pct
        description: 'Original: % climat constat'
      - name: biodiversite_pct
        description: 'Original: % biodiversite'
      - name: biodiversite_constat_pct
        description: 'Original: % biodiversité constat'
      - name: biodiversite_solutions_pct
        description: 'Original: % biodiversité solutions'
      - name: biodiversite_consequences_pct
        description: 'Original: % biodiversité conséquences'
      - name: biodiversite_causes_pct
        description: 'Original: % biodiversité causes'
      - name: ressources_pct
        description: 'Original: % ressources'
      - name: ressources_constat_pct
        description: 'Original: % ressources constat'
      - name: ressources_solutions_pct
        description: 'Original: % ressources solutions'

  - name: core_query_thematics_keywords
    description: >
      Thematic keyword analysis by channel and week, 
      including crisis type, theme, and keyword frequency.
    columns:
      - name: channel_title
        description: Title of the broadcast channel.
      - name: week
        description: Week of the observation (likely in YYYY-WW format).
      - name: crise_type
        description: Type of crisis being referenced.
      - name: theme
        description: Thematic category associated with the keyword.
      - name: category
        description: Sub-category or secondary classification for the keyword.
      - name: keyword
        description: The keyword identified in the broadcast or transcript.
      - name: count
        description: Count of lines or mentions related to the keyword
      - name: sum_duration_minutes_week
        description: Number of program minutes for the week

  - name: core_query_thematics_keywords_i8n
    description: >
      International thematic keyword analysis by channel and week, 
      including crisis type, theme, and keyword frequency.
    columns:
      - name: channel_title
        description: Title of the broadcast channel.
      - name: week
        description: Week of the observation (likely in YYYY-WW format).
      - name: crise_type
        description: Type of crisis being referenced.
      - name: theme
        description: Thematic category associated with the keyword.
      - name: category
        description: Sub-category or secondary classification for the keyword.
      - name: keyword
        description: The keyword identified in the broadcast or transcript.
      - name: count
        description: Count of lines or mentions related to the keyword.
      - name: country
        description: country

  - name: task_global_completion
    description: "Aggregates data between the labelstudio tasks and the labelstudio task completions."
    columns:
      - name: task_aggregate_id
        description: "Unique ID for the aggregated task. Generated from a hash of task_id, project_id and country"
      - name: created_at
        description: "Creation timestamp"
      - name: updated_at
        description: "Update timestamp"
      - name: is_labeled
        description: "Boolean, has the task been labeled "
      - name: project_id
        description: "Project ID for the country in the original labelstudio instance."
      - name: country
        description: "name of the country of origin"
      - name: data_item_id
        description: "ID from keywords "
      - name: data_item_channel
        description: "Channel ID"
      - name: data_item_channel_name
        description: "Channel name lowercase"
      - name: data_item_channel_title
        description: "Name of Channel properly formatted"
      - name: data_item_channel_program
        description: "Name of program from which the chunk is extracted"
      - name: data_item_channel_program_type
        description: "Type of program (news, opinion, continuous news, talk show)"
      - name: data_item_day
        description: "Day of month"
      - name: data_item_month
        description: "Month of year"
      - name: data_item_year
        description: "Year of the segment"
      - name: data_item_model_name
        description: "Name of model used for the classification"
      - name: data_item_model_reason
        description: "Model reason for classification or model probability score"
      - name: data_item_model_result
        description: "Model classification"
      - name: data_item_plaintext
        description: "Segment transcript obtained from mediatree"
      - name: data_item_plaintext_whisper
        description: "Segment transcript obtained from the speech-to-text model."
      - name: data_item_start
        description: "Start timestamp for the segment"
      - name: data_item_url_mediatree
        description: "Mediatree url with link to the video"
      - name: mesinfo_choice
        description: "Choice between correct and incorrect. Note this applies to the model's classification: Correct = Misinformation and Incorrect = Not Misinformation"
      - name: locuteur_choice
        description: "Speaker types identified"
      - name: mesinfo_correct
        description: "One hot encoding mesinfo correct"
      - name: mesinfo_incorrect
        description: "One hot encoding mesinfo incorrect"
      - name: speaker_journalist
        description: "One hot encoding speaker journalist"
      - name: speaker_commentator
        description: "One hot encoding speaker commentator"
      - name: speaker_guest
        description: "One hot encoding speaker guest"
      - name: speaker_politician
        description: "One hot encoding speaker politician"
      - name: speaker_audience
        description: "One hot encoding speaker audience"
      - name: speaker_unknown
        description: "One hot encoding speaker unknown"
      - name: "Annotation Version"
        description: "Annotation version (first annotation=1, second annotation=2)"
      - name: sum_duration_minutes
        description: "Total weekly durations (minutes) for the program being annotated"
      - name: weekly_perc_climat
        description: "% Time the of sum_duration_minutes being dedicated to climate change"

  - name: environmental_shares_with_desinfo_counts
    columns:
      - name: "start"
        description: "Start of week timestamp."
      - name: channel_title	
        description: "Name of Channel properly formatted."
      - name: channel_name	
        description: "Name of Channel."
      - name: sum_duration_minutes
        description: "Total weekly durations (minutes) for the channel on a given week."
      - name: weekly_perc_climat
        description: "% Time the of sum_duration_minutes being dedicated to climate change."
      - name: country
        description: "Country of channel."
      - name: total_mesinfo
        description: "Total instances of misinformation detected."