channel_titles_france = {
    "tf1": "TF1",
    "france2": "France 2",
    "fr3-idf": "France 3-idf",
    "m6": "M6",
    "arte": "Arte",
    "d8": "C8",
    "bfmtv": "BFM TV",
    "lci": "LCI",
    "franceinfotv": "France Info TV",
    "itele": "CNews",
    "europe1": "Europe 1",
    "france-culture": "France Culture",
    "france-inter": "France Inter",
    "sud-radio": "Sud Radio",
    "rmc": "RMC",
    "rtl": "RTL",
    "france24": "France 24",
    "france-info": "FranceinfoRadio",
    "rfi": "RFI",
}